# Refuse a commit that stages a file over 5 MB.
#
# 🛑 UNVERIFIED as written — see .claude/README.md for the two-command test that
# proves it fires. A guard nobody has watched fail is not a guard.
#
# Exit 0 = allow, exit 2 = block (Claude Code treats a non-zero PreToolUse exit
# as a refusal and shows stderr to the model).
#
# Why 5 MB: one commit took this repo to 194 MB. `data/derived/` is gitignored and
# every .db is rebuildable, so nothing legitimate in this project is that large
# except the two committed DBC extracts, which are already tracked and therefore
# only appear staged when they genuinely change.

$ErrorActionPreference = 'Stop'
$LIMIT_BYTES = 5MB

# Allowed large files: the committed DBC extracts are ~16 MB and ~30 MB by design.
# They can ONLY be regenerated by an owner-gated --with-dbc run, so a staged change
# to them is deliberate. Anything else over the limit is an accident.
$ALLOW = @(
  'data/source/dbc/dbc-extract.json',
  'data/source/dbc/dbc-ascension-extract.json'
)

try {
    $staged = git diff --cached --name-only 2>$null
} catch {
    exit 0          # not a git repo, or git unavailable — never block on that
}
if (-not $staged) { exit 0 }

$offenders = @()
foreach ($path in $staged) {
    if ($ALLOW -contains $path) { continue }
    if (-not (Test-Path -LiteralPath $path)) { continue }   # deletion or rename
    $item = Get-Item -LiteralPath $path
    if ($item.PSIsContainer) { continue }
    if ($item.Length -gt $LIMIT_BYTES) {
        $mb = [math]::Round($item.Length / 1MB, 1)
        $offenders += ("  {0}  ({1} MB)" -f $path, $mb)
    }
}

if ($offenders.Count -gt 0) {
    $msg = @(
        "BLOCKED: staged file(s) over 5 MB:",
        ($offenders -join "`n"),
        "",
        "Nothing in this repo should be this large except the two committed DBC",
        "extracts. If this is a built database or an extract dump, unstage it and",
        "check .gitignore. If it genuinely belongs in the repo, add it to `$ALLOW",
        "in .claude/hooks/block_large_staged_files.ps1 and say why in the commit."
    ) -join "`n"
    [Console]::Error.WriteLine($msg)
    exit 2
}

exit 0
