#!/usr/bin/env python3
"""Seeds class_origin / best_fit_path / confirmed_facts strictly from statements
already made in Ascension_Context_Primer.md and Ascension_Paladin_Handoff.md.
Nothing here is guessed — every row traces to a doc + section."""
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).resolve().parent / 'ascension_index.db'  # this file lives in index/
conn = sqlite3.connect(str(DB_PATH))
cur = conn.cursor()

# (spell_id, class_origin, confidence, note)
CLASS_ORIGIN = [
    (903158, 'Paladin', 'confirmed_class_tag_rule', 'Borrows Crusader Strike modifiers; feeds Hammerdin. Primer §4 / Handoff §2.'),
    (907894, 'Rogue',   'predicted_class_tag_rule', 'Borrows Sinister Strike modifiers; does NOT feed Hammerdin proc. Primer §4.'),
    (904880, 'Rogue',   'predicted_class_tag_rule', 'Borrows Eviscerate modifiers; does NOT feed Hammerdin proc. Primer §4.'),
    (907300, 'Warrior', 'confirmed_proc_test',      'Borrows Cleave modifiers. CONFIRMED zero procs from "damaging Paladin abilities" trigger. Primer §4 / Handoff §2.'),
    (907780, 'Warrior', 'predicted_class_tag_rule', 'Borrows Whirlwind modifiers; does NOT feed Hammerdin proc. Primer §4.'),
    (913444, 'Warrior', 'confirmed_class_tag_rule', 'Borrows Bladestorm modifiers; does NOT feed Hammerdin. Also a channelled lockout ability - suppresses narrow-intake engines while active. Primer §4 / Handoff §2.'),
    (276066, 'Warrior', 'confirmed_class_tag_rule', 'Fel Cleave - borrows Cleave modifiers. Export tooltip omits the clause entirely (same pattern as Enhanced Weapon Mastery, Primer §2); found via DBC pipeline, not a live screenshot. Not part of current Paladin kit (Shadowflame school). Primer §4 (v11).'),
    (20473,  'Paladin', 'confirmed_native',         'Native Paladin ability. Handoff §2.'),
    (280210, 'Physical', 'confirmed_native',        'Judgement of the Three Hammers - triggered by "any direct damage" (wide intake), crits on Physical/melee table. Handoff §4/§9.'),
    (26573,  'Paladin', 'confirmed_native',         'Native Paladin ability (Consecration). Handoff §12 - "Consecration earns its slot" (v4 verdict overturned).'),
    (853486, 'Paladin', 'confirmed_native',         'The Art of War - Handoff §12, v4 "dead" verdict overturned (cut on wrong tooltip clause).'),
    (282984, 'Paladin', 'confirmed_native',         'Hour of Judgement - core Paladin cooldown, triggers hidden sub-spell "Hammer from the Heavens" (282987, not in catalog export). Handoff §1/§4/§12.'),
    (276076, 'Duality', 'confirmed_native',         'Fel Infused Weapon - hybrid AP*0.05+SP*0.05+flat Shadowflame proc, no ICD in tooltip, fires on every auto attack AND melee ability. Primer §1 (v6).'),
    (272624, 'Shaman',  'confirmed_class_tag_rule', 'Molten Earth - live tooltip confirms "uses Fire Nova modifiers". Triggered by Lava Lash (Shaman) but NOT modified by Lava Lash talents (Elemental Fusion, Lava Flows) - class-tag rule proof case #2, Primer §4. Formula: 60+(SP+AP)*0.12 Fire dmg/tick, 8 ticks.'),
    (907280, 'Warrior', 'confirmed_class_tag_rule', 'Voidbound Cleave - export tooltip explicitly states "This uses Cleave modifiers." Fourth class-tag proof case alongside Lightbound Cleave/Fel Cleave (Primer §4): weapon damage + $s1 Shadowstrike (hybrid physical+magic) damage to target + nearest ally/allies, Warrior-tagged despite the Void/Shadowstrike flavor. Primer §4 (2026-08-03, Pumprat scouting session).'),
]

BEST_FIT_PATH = [
    (903158, 'Duality', 'Physical+Holy hybrid via Crusader Strike base - benefits from AP and Holy SP exposure. Inferred from build context, not an explicit path statement.'),
    (272624, 'Duality', 'Pure Fire school but carries both SP*0.12 and AP*0.12 per-tick coefficients - hybrid AP+SP scaling is not exclusive to named -strike schools (Primer §1, v7). Benefits from Duality itemization despite not being a hybrid-named school.'),
]

cur.executemany('''UPDATE spells SET class_origin=?, class_confidence=?, notes=?
                    WHERE id=?''',
                 [(co, conf, note, sid) for (sid, co, conf, note) in CLASS_ORIGIN])

for sid, path, note in BEST_FIT_PATH:
    cur.execute('UPDATE spells SET best_fit_path=?, notes=COALESCE(notes,"")||? WHERE id=?',
                (path, ' | PATH: ' + note, sid))

FACTS = [
    ('crit_conversion', 'Crit rating: 14.0 rating per 1%, identical melee and spell (measured: 393->28.07%, 164->11.71%).', 'Primer', '§1'),
    ('hit_cap', 'Special-attack (yellow) hit cap vs raid boss: 8%. Dual-wield white attacks carry +19% miss on top - DW auto-attacks can be near-worthless (measured 4.2% of damage).', 'Primer', '§1'),
    ('expertise_cap', 'Expertise dodge cap: 26.', 'Primer', '§1'),
    ('periodic_no_crit', 'Ground/periodic effects generally cannot crit - confirmed repeatedly for aura-tick DoTs (PBL ground 0%/32 ticks; Righteous Vengeance 0% over 4 parses). CONFIRMED EXCEPTION, mechanism theory RETRACTED (v7): Molten Earth live tooltip is a textbook aura-tick DoT ("60+(SP+AP)*0.12 Fire dmg every second for 8 sec, uses Fire Nova modifiers") - structurally identical to Righteous Vengeance - yet parses 40.7% crit over 575 hits vs Righteous Vengeance 0% over 4 parses. The v6 "aura-tick vs instant-pulse ground object" theory does NOT survive this; no structural predictor found. Crit-capability appears to be a per-spell server-side flag. Verify per ability from a parse, never infer from tooltip structure.', 'Primer', '§1'),
    ('fel_infused_weapon_scaling', 'Fel Infused Weapon: guaranteed Shadowflame proc on every auto attack AND melee ability, no ICD stated in tooltip, for [flat + AP*0.05 + SP*0.05]. Scales directly with attack frequency rather than weapon damage - reported up to ~30% of total DPS for hyper-fast dual-wield attackers in group parses. Strong argument for maximizing weapon speed independent of weapon DPS when a build carries this or similar no-ICD per-hit cards. Always check for an ICD before assuming a per-hit proc is diluted by faster/smaller hits.', 'Primer', '§1 (v6)'),
    ('holy_unresistable', 'Holy is unresistable - Spell Penetration worthless against it.', 'Primer', '§1'),
    ('hybrid_school_rule', 'Hybrid abilities (Holystrike, Holyfire, Shadowflame, Firestrike, Froststrike, Shadowstrike, Spellstrike, Stormstrike) have two damage components (physical weapon half + magic school half) and double-dip modifiers from BOTH component schools. They are NOT classified as Spells for gating/trigger purposes even though the magic half exists.', 'Primer', '§1'),
    ('hybrid_crit_table', 'RESOLVED: hybrid strikes (Holystrike) crit on the SPELL table, not melee, and take Holy modifiers. Method: parse crit% per source, sort against sheet melee/spell values. Spell crit rating can be worth several times melee crit rating in a hybrid build.', 'Primer', '§1 / §5', ),
    ('class_tag_rule', "A card's \"uses X modifiers\" line predicts its class tag, NOT its flavour/name/damage school. Confirm with a dummy proc count. sharesModifiersWith opens cross-class talent chase surfaces.", 'Primer', '§4'),
    ('engine_intake', 'Narrow intake (e.g. "damaging Paladin abilities") only accepts same-class-tagged buttons - a build can starve its own engine without noticing. Wide intake (e.g. "dealing direct damage") accepts everything. Always map engine intake against the actual rotation.', 'Primer', '§4'),
    ('channelled_lockout_poison', 'Abilities worded "cannot perform any other abilities" (Bladestorm-family) suppress every narrow-intake proc engine for the whole channel - can show as top damage source in a parse while being net-negative. Compare total damage across rotations, never per-ability shares.', 'Primer', '§4'),
    ('exclusivity_bucket_alldamage', 'Enhanced Weapon Mastery <-> Unending Fury <-> Answered Prayers <-> Blessed Weapons all share an all-damage% "does not stack / highest applies" bucket. Similar wording on Holy Focus and Dual Wield Specialization <-> Dual Wield Mastery (fully redundant, one always dead).', 'Primer', '§2'),
    ('lucky_flag_falsified', 'LUCKY family flag theory FALSIFIED - Divine Steed (no-LUCKY) rolls repeatedly. Working roll model is rarity x affinity only.', 'Primer', '§2'),
    ('duplicate_name_trap', 'Distinct cards can share a name across classes (Vengeance: Paladin r3 stacking-damage vs Druid r5 spell-crit-damage). Ascension can also reuse a retail/classic name for a totally different mechanic - Mental Quickness here is a physical<->magic ping-pong buff, NOT the WotLK AP->SP converter. Always read the actual tooltip; never assume from name.', 'Primer', '§2'),
    ('export_tooltip_incomplete', 'Export tooltips can OMIT entire clauses, not just leave $s1 unresolved. Enhanced Weapon Mastery export reads only the damage% line - the live tooltip adds the exclusivity clause that turns it from top-tier to a dead slot. Get a live tooltip screenshot before any final card verdict.', 'Primer', '§2'),
    ('path_strength', 'Path of Strength: flat Str (4 + 0.5/lvl, ~34@60); AP = 100% of Strength; Str->Parry. 1H: +20% ArP. 2H: melee/ranged physical abilities +10%.', 'Primer', '§3'),
    ('path_agility', 'Path of Agility: flat Agi (same curve); AP = 100% of Agility; Agi->crit chance AND crit damage. 1H: -8% GCD/cost on damaging melee/ranged abilities. 2H: +20% ability crit damage.', 'Primer', '§3'),
    ('path_duality', 'Path of Duality (tooltip claims): AP = highest of Str/Agi; Int->melee/ranged crit; Agi->spell crit; casting no longer resets swing timer. 2H: +6% magic AND physical damage. 1H: +10% haste. v4 SP amp (x1.75) and cross-crit conversion claims RETRACTED - not visible on a live sheet (Handoff §4 URGENT: may not be active at all, verify in-game). Mental Dexterity (talent card) independently implements the same Int->melee crit / Agi->spell crit conversion and can be used regardless of whether the path passive is confirmed live.', 'Primer', '§3 / Handoff §4'),
    ('path_intelligence', 'Path of Intelligence: bonus SP/Int/Spirit (flat Int 4+1.25/lvl ~79@60; Spirit ~40); SP from items/effects DOUBLED. 2H: +12% spell haste. 1H: +5% spell damage.', 'Primer', '§3'),
    ('path_healing', 'Path of Healing: enables Healer role; Healing Power is a distinct gated stat (off-path healing = emergency top-offs only). Flat Int/Spirit like Intelligence path. 2H: +10% spell haste, +3% spell crit. 1H: +5% healing.', 'Primer', '§3'),
    ('path_rules_misc', '"Abilities" wording in path bonuses excludes auto-attacks (yellow only); "Damage done" wording includes autos. Titan\'s Grip/double-2H counts as 2H for path clauses. Path switching is free and instant - always verify active path on the sheet before reasoning from grants.', 'Primer', '§3'),
    ('rv_findings', 'Righteous Vengeance: 30% of crit damage over 8s as Holy DoT. 0% crit across 4 parses (confirms periodic/no-crit rule). 92-101% uptime, pools on refresh (Ignite/Deep Wounds style, does not clip). Measured 6.4-9.0% of total damage. Raises marginal crit value from 2.0x to 2.6x a normal hit.', 'Handoff', '§4'),
    ('paladin_crit_exposure', 'Paladin build v5 crit-table exposure from King Gordok parse: Spell table 70.2%, Melee table 14.3%, Cannot-crit 15.3% (Righteous Vengeance, Holy Vengeance DoT, Hour of Judgement, Consecration).', 'Handoff', '§4/§9'),
    ('paladin_stat_weights', 'Paladin v5 stat weights (combined per-rating value, hit/crit are unified melee+spell on this server): Crit Rating 2.00 (best stat, not close) | Weapon DPS 2.6 | AP 1.00 | Str 1.00 | SP 1.00 (->1.77 if Duality amp restored) | Holy SP 0.95 | Int 0.50 | Haste 0.50 | Hit 0.30 (0.00 for dungeon content, raid only) | Expertise 0.30 (provisional) | Armor Pen 0.18 | Agi 0.15 | Stamina 0.15 | Mana/5 0.10 | Spirit/Spell Pen/Resil 0.00.', 'Handoff', '§10'),
    ('hit_expertise_walkback', 'Crit table and hit table are INDEPENDENT rolls - Holystrike critting on spell table does not mean it rolls spell hit. Only ~5.4% of the Paladin v5 parse damage is confirmed spell-hit-gated (Holy Shock+Judgement). Melee-table hybrid abilities use melee hit (already capped). Periodic effects cannot miss. Procs riding an already-landed attack do not re-roll. Summoned procs (Hammer from the Heavens, JotTH, ~29% of damage) are UNRESOLVED whether they roll a hit check at all - decides whether raid Hit weight is ~0.0 or ~1.2.', 'Handoff', '§10'),
    ('hidden_subspell_hoth', 'Hammer from the Heavens (triggered by Hour of Judgement) has a hidden sub-spell ID 282987 not present in the catalog export - its exact SP/AP/flat composition is UNCONFIRMED, currently assumed 30% SP / 30% AP / 40% flat pending a live tooltip.', 'Handoff', '§10/§12'),
    ('rotation_error', 'Biggest identified free DPS gain (v5): Judgement and Holy Shock were pressed only ~3 times each in a 309s fight vs an expected ~38 and ~50 - starving the Hammerdin engine that brings back Hour of Judgement.', 'Handoff', '§11'),
    ('method_crit_table_id', 'Cheapest mechanics test available: parse crit% per source, sort against the sheet\'s melee and spell crit values in one combat log - immediately reveals which table each ability uses; 0% crit reveals a periodic effect. Settled the Holystrike crit-table question after 2 doc versions "under review". CORRECTION (v7): a nonzero crit% on a periodic/ground effect is NOT reliable evidence it differs structurally from a normal aura tick - Molten Earth is a confirmed aura-tick DoT that still crits. Use crit% to sort spell-vs-melee table, not to infer implementation.', 'Primer', '§5'),
    ('method_sample_size', 'Crit-rate questions need thousands of hits to test; damage-multiplier questions need ~100. If candidate values are within ~3 points, find a different discriminator.', 'Primer', '§5'),
    ('method_no_reroll_to_measure', 'Never reroll a card to measure it - no respec lever exists and multi-rank cards can return lower. Prefer: character-sheet breakdown tooltips -> gear swaps -> consumables -> buff-state filtering -> two-target comparisons -> bar toggles.', 'Primer', '§5'),
    ('rank_mechanics', 'A card guarantees the MAX RANK of a talent (that\'s the reason to slot one) - X/Y shown is the ROLL result, not spent points, and there is no respec lever. Rolling an upgrade on a held partial-rank card refunds the reroll if it hits; partial-rank talents reportedly have a higher chance of rolling their own upgrade. A 1/1 single-rank card is a cheaper acquisition than chasing a 5-rank card to max.', 'Primer', '§2'),
    ('method_check_icd_before_dilution', 'Before assuming a per-hit proc is diluted by faster/smaller attacks, check whether it has a stated ICD. No-ICD per-hit procs (Fel Infused Weapon, v6) scale UP with attack frequency - the opposite of the usual averaging intuition.', 'Primer', '§5'),
    ('class_tag_proof_case_2', 'Molten Earth is triggered by Lava Lash (Shaman) but its own tooltip confirms "uses Fire Nova modifiers" - a DIFFERENT modifier bucket. Elemental Fusion and Lava Flows buff Lava Lash directly but do NOT buff Molten Earth, despite the trigger relationship. A recommendation assuming otherwise was made and retracted same-session. Corollary: never assume a spawned/triggered secondary effect inherits its trigger\'s modifier bucket by proximity - check its own "uses X modifiers" line independently. Second proof case for the class-tag rule alongside Lightbound Cleave/Cleave.', 'Primer', '§4 (v7)'),
    ('hybrid_ap_sp_not_strike_exclusive', 'AP+SP dual scaling is not exclusive to the named hybrid -strike schools (Holystrike/Firestrike/etc). Molten Earth (pure Fire, 60+(SP+AP)*0.12/tick) and Cataclysmic Sundering (pure Fire ground patch) both mix AP+SP coefficients without being -strike schools. Do not use "-strike naming" as a proxy for "has dual AP+SP scaling" - check raw tooltip coefficients directly every time.', 'Primer', '§1 (v7)'),
    ('weapon_imbue_exclusivity', 'Weapon-imbue-type ability cards (Windfury Weapon, Flametongue Weapon, Fel Infused Weapon, Rockbiter Weapon, Frostbrand Weapon) share a weapon-enchant slot - only one active at a time. This is a mechanical slot conflict, separate from the talent all-damage% exclusivity bucket, and is NOT stated in any single tooltip - ask "is this an imbue?" before recommending one alongside another.', 'Primer', '§2 (v7)'),
    ('method_prefer_named_effect_talents', 'When hunting multipliers for a specific effect (e.g. Shadowflame damage), prefer talents that name the effect verbatim in their tooltip (Shadow and Flame, Bane both list "Shadowflame" explicitly) over talents matched by generic school wording (Emberstorm: "Fire and Shadow spells", does not name Shadowflame - a prediction under the hybrid double-dip rule, not a confirmed hit). Named lists are ground truth; generic wording needs a proc-test.', 'Primer', '§5 (v7)'),
    ('method_rank_id_decoding', 'When decoding a live in-game spell ID export (WeakAura, inspect addon) against the catalog, an unresolved ID is very likely a different rank of a known card, not missing content. Multi-rank talents appear to get a distinct spellID per rank in-game while the catalog stores one canonical ID per card. Check +/-1-3 of the unresolved ID for a known card name before concluding absence. Resolved 5/5 unmatched IDs this way in one live cross-check (Flurry, Vengeance, Fanaticism, Spellblade, Mental Quickness), each landing exactly on a card already known to be held at partial rank.', 'Primer', '§5 (v8)'),
    ('paladin_v6_loadout_confirmed', 'Live inspect/WeakAura export (55 spell IDs) cross-referenced against catalog for Paladin build, 2026-08-02. 22 of 25 v5 board talents confirmed unchanged. Shadow Strikes, Enhanced Weapon Mastery, and Seals of the Pure confirmed rerolled away since v5, replaced by Accuracy, Glyph of Seal of Command (deliberate temporary mana fix pending Spellblade 3/3), and Glyph of Blood Strike (unevaluated filler). Lunar Guidance independently confirmed slotted, matching the v5 hypothesis for the residual Duality SP gap. Berserker Stance, Ghost Wolf, Frostfall confirmed present but player-rated as low-priority leftovers, not core rotation.', 'Handoff', '§7/§12 (v6)'),
    ('goak_avenging_wrath_retraction', 'RETRACTED (v7): "Avenging Wrath / Guardian of Ancient Kings are substitutes, take the first" was wrong. They are independent cooldowns on separate systems - Guardian of Ancient Kings resets/discounts Hammer of the Righteous, Divine Storm, and Holy Shock cooldowns plus a Holy damage buff; Avenging Wrath is a flat all-damage/healing cooldown on its own timer. Both tooltips carry a "does not stack with other similar effects" clause, but that governs multiple instances of the SAME buff type, not necessarily exclusivity between these two specifically - and even under a worst-case mutual-exclusivity reading, sequential use on two separate cooldowns still nets more total burst-window uptime than picking only one. Both moved to the Paladin handoff chase list.', 'Handoff', '§8/§12 (v7)'),
    ('cross_character_ewm_observation', 'Cross-character observation (not a measurement, treat as evidence): Enhanced Weapon Mastery confirmed live (undisputed) on another player\'s comparable Paladin/Hammerdin spec, since his board carries none of the all-damage% exclusivity bucket\'s other members (no Answered Prayers, Unending Fury, Blessed Weapons, Blood Gorged, Improved Blood Presence). Same card is dead on our own build (bucket-blocked by Answered Prayers). Illustrates that a card\'s dead/alive status depends on full board composition, not the card in isolation.', 'Handoff', '§12 (v7)'),
    ('divine_storm_execution_sentence_sighting', 'Cross-character observation (not a measurement): another player\'s comparable Paladin/Hammerdin spec runs both Divine Storm and Execution Sentence live - both are on our own ability chase list (§8). Evidence they are obtainable and playable; not a substitute for our own parse data once acquired.', 'Handoff', '§8 (v7)'),
    ('doomhammers_fury_does_not_touch_molten_earth', 'Doomhammer\'s Fury (271580, granted by the Casting-Lava-Lash talent 271596) does NOT buff Lava Lash or Molten Earth. Raw DBC description (271580): "Your Pyroblast and Lava Burst now restore mana, generate a stack of Maelstrom Weapon, and deal $s1% increased direct damage" (EffectBasePoints[0]=12 -> s1=13%; EffectAura=[Dummy,ProcTriggerSpell,ProcTriggerSpell] triggering 271589 and 271587 for the mana-restore/Maelstrom-Weapon-stack grants). Confirmed NOT an amplifier for either Lava Lash or its Molten Earth spawn - third instance of the class-tag trigger-vs-modifier trap (primer §4 proof case #2 pattern: granted-by-X does not imply buffs-X). CONFIRMED via 2026-08-03 DBC pull (Titanus/Zavulon armory scouting session, report 74).', 'DBC pull', '2026-08-03 session'),
    ('fel_infused_weapon_flat_and_2h_coefficients', 'Fel Infused Weapon (276076) tooltip formula ${$276075ppl1+$276075m1+$AP*0.05+$SP*0.05}: the AP*0.05/SP*0.05 terms were already in spell_scaling (source=export_tooltip). Raw DBC for hidden sub-spell 276075 ("Fel Infused Attack", school_mask=36 = Shadow+Fire hybrid): EffectBasePoints[0]=3, EffectDieSides[0]=3, EffectRealPointsPerLevel[0]=1.5 -> $276075m1 (min roll, basepoints+1) = 4, $276075M1 (max roll) = 6, $276075ppl1 = 1.5. Flat component ~5.5 (before AP/SP terms) at effective scaling level. Separately, 276082 ("Fel Infused Flames 2H damage increase", a % damage-done aura) has EffectBasePoints[0]=14 -> $276082s1 = 15% more Shadowflame damage while a single two-handed weapon is equipped. CONFIRMED via 2026-08-03 DBC pull (Titanus/Zavulon armory scouting session, report 74).', 'DBC pull', '2026-08-03 session'),
    ('fire_strike_not_part_of_fel_infused_weapon', 'Searched the FULL client Spell.dbc (209,080 records, not just the 3,061-entry spell-export.json catalog) for every spell named "Fire Strike" - 50 name matches total, none scoped near 276075/276076/276082 and none appear in either spell\'s own EffectTriggerSpell array ([0,0,0] on both). Structurally, "Fire Strike" is NOT a second effect slot on Fel Infused Weapon\'s spell entry, nor a documented trigger of it. Fel Infused Attack (276075) is itself already a hybrid Shadow+Fire spell (school_mask=36); the client\'s combat log has no DBC-level mechanism to split one hybrid-school hit into two separately-named rows. The most structurally plausible unrelated candidate is the "lance of fire" item-proc family (spell IDs 313765/317765/321765, triggered by 313764/317764/321764 - "melee attacks have a chance to unleash a lance of fire... SP*0.16+AP*0.1 Fire damage", no ICD stated, pure Fire school), which would produce a coincidentally similar hit-count profile from a SEPARATE item/enchant rather than from Fel Infused Weapon itself. UNRESOLVED which exact "Fire Strike" ID logged for Zavulon without the actual spell ID from the raw combat-log API (name search alone is ambiguous across 50 candidates) - do NOT sum the Fire Strike row into Fel Infused Weapon\'s "~30% of total DPS" figure on this evidence; treat as a separate proc pending spell-ID confirmation from the log data. CONFIRMED-NEGATIVE via 2026-08-03 DBC pull (Titanus/Zavulon armory scouting session, report 74).', 'DBC pull', '2026-08-03 session'),
    ('righteous_vengeance_zero_crit_reinforced', 'Righteous Vengeance 0% crit reinforced far beyond the original sample: 303 total hits, 0 crits, across 9 different characters (Titanus, Zyzz, Blix, Professorpp, Zavulon, Lootgoblin, Wynta, Xyz, Bigolecrits) spanning 4 different Paths (Duality, Strength, Intelligence, Agility). Path-independence makes this essentially settled, not just "still holding." SOURCE: 2026-08-03 scouting session, report 74 (Hakkar).', 'Scouting', '2026-08-03 session'),
    ('molten_earth_crit_varies_by_character', 'Molten Earth crit rate is NOT a fixed/flagged value - it varies by character: 40.7% (575 hits, original primer v6/v7 sample), 46.6% (54/116, Zavulon/Duality), 64.8% (35/54, Titanus/Intelligence). Three independent measurements spanning a 24-point range. This REFINES (does not contradict) the existing "no structural predictor, per-spell server flag, verify per-parse" verdict - the more precise read is that Molten Earth is a normal crit-capable spell that scales with each character\'s own spell crit rating, same as any other spell, rather than having some fixed or capped crit value. SOURCE: 2026-08-03 scouting session, report 74.', 'Scouting', '2026-08-03 session'),
    ('holy_unresistable_means_no_full_resist', 'REFINEMENT to the existing "Holy is unresistable" combat-engine default (primer §1): confirmed via avoidance data that this specifically means no FULL resist roll, not immunity to partial/chip magic resistance. Lightbound Cleave (Holystrike, our own build): 356 hits across 3 targets, 0 miss/dodge/parry/resist_full, but nonzero partial resist (133/25/1 per target - damage reduced by a %, not avoided). Hammer from the Heavens (Holystrike, our own build, 11 characters pooled): 4,962 hits, 0 miss/dodge/parry/resist_full, 698 partial resists. Practical consequence: "unresistable" does not mean "ignore target resistance stat entirely" for damage forecasting, only "cannot be fully negated by a resist roll." SOURCE: 2026-08-03 scouting session, reports 59-86 (17 reports scanned).', 'Scouting', '2026-08-03 session'),
    ('hammer_from_heavens_cannot_be_avoided', 'CONFIRMED, closes build_paladin-hammerdin.md open question (hit/expertise walkback §): Hammer from the Heavens cannot miss, be dodged, or be parried. 4,962 total landed hits pooled across 11 characters (Professorpp 2471, Geniusdex 988, Phantomx 774, Germarona 239, Linny 73, Xoller 49, Zenji, Chewy, Skipper, Scytrix, Givemegood) and 17 reports (ids 59-86): 0 miss_count, 0 dodge_count, 0 parry_count, 0 resist_full_count across the entire pool. Only partial/chip resist is nonzero (698 total) - see holy_unresistable_means_no_full_resist. This is a hit-table/avoidance-type finding, not a crit-table finding - crit table for Hammer from the Heavens was already separately confirmed via Holystrike (primer §1 v4). SOURCE: 2026-08-03 scouting session, character_damage_taken_abilities endpoint with participantType=enemies.', 'Scouting', '2026-08-03 session'),
    ('titanic_mutilate_first_crit_data', 'Titanic Mutilate (external sighting, borrows Mutilate modifiers per class-tag rule, Physical school) has its first real crit data: main-hand 47.8% (11/23), off-hand 39.1% (9/23), on Zavulon/Duality. Consistent with melee-table crit given Physical school - not yet cross-checked against that character\'s own melee/spell crit sheet split, so treat as suggestive not confirmed-table. SOURCE: 2026-08-03 scouting session, report 74.', 'Scouting', '2026-08-03 session'),
    ('winds_of_winter_killing_machine_correlation_v2', 'Second independent sample supporting (not yet confirming) Killing Machine as the driver of Winds of Winter\'s near-100% crit rate: Titanus logged 12 Winds of Winter casts (15 hits, 15 crits = 100%) against 11 Killing Machine applications (55.8% average uptime) in the same fight - close to 1:1, consistent with a hold-for-proc playstyle. Does not fully prove the mechanism (would need cast-timestamp-vs-buff-interval overlap, which this API does not expose at that granularity). Existing primer/synergy doc open question stands, now with a second corroborating N. SOURCE: 2026-08-03 scouting session, report 74, buff_uptimes endpoint.', 'Scouting', '2026-08-03 session'),
    ('combat_log_parser_field_layout_fix', 'combat_log_parser.py verified and fixed against a real 2026-08-03 Ascension log (Pumprat, Uldaman). Two bugs found: (1) this Ascension client omits sourceRaidFlags/destRaidFlags entirely - 6 base fields not the stock-WotLK 8, which had silently shifted spellId/amount/critical etc. by 2 columns and produced garbage tiny "spellIds" (223, 220...) with a flatlined 0% crit everywhere. (2) miss-type events are SPELL_MISSED/SWING_MISSED in this log, not SPELL_MISS/SWING_MISS - the old checks never matched, so avoidance_breakdown silently returned nothing for spell misses. Also decode_alc.py: the chunk-reassembly regex was capturing the CSV field\'s closing quote as part of the base64 payload, breaking the group-of-4 length on nearly every frame (0 build records decoded before the fix, 625 after). All three fixed same-session; see tools/log_parser/README.md.', 'Tooling', '2026-08-03 session (Pumprat log)'),
    ('fel_infused_weapon_avoidance_at_scale', 'Fel Infused Attack (276075, Fel Infused Weapon\'s proc) avoidance data at far larger scale than any prior sample: 1,823 hits, 0 miss/dodge/parry/full-resist - only 13 REFLECT events (a different mechanic, target-side spell reflection, not a normal avoidance roll). Strongly reinforces the existing "no-ICD per-hit procs do not roll an avoidable hit check" read (primer §1 v6) with real hit-count volume instead of tooltip-absence inference alone. Crit rate 23.86% (435/1823) - notably BELOW both this character\'s melee-table baseline (~45.63%, from Melee/Sword Specialization/Hammer of the Righteous all clustering 44-46%) and typical hybrid-school rates seen elsewhere (~50-53%). Open question, not yet resolved: why Fel Infused Attack crits well below the melee-table baseline despite being a guaranteed per-hit proc - possibly a crit source that does not benefit from the same crit-rating pool as normal attacks/abilities. SOURCE: 2026-08-03 combat log, character Pumprat, Uldaman.', 'Scouting', '2026-08-03 session (Pumprat log)'),
    ('voidbound_cleave_crit_signal', 'Voidbound Cleave (907280, Warrior-tagged via "uses Cleave modifiers", see class_origin) crit rate 60.65% (501/826) on Pumprat - about 15 points above this character\'s own melee-table baseline (~45.63%, Melee/Sword Specialization/Hammer of the Righteous cluster 44-46%). Also rolls a real avoidance check (8 dodge, 2 parry out of 836 attempts) confirming it is NOT unavoidable like a periodic/summoned effect. Directionally consistent with the existing "hybrid strikes crit on the spell table" pattern (primer §1 v4, established for Holystrike) extending to Shadowstrike as well, given Voidbound Cleave is tooltip-confirmed physical-weapon-damage + Shadowstrike magic-damage hybrid - but NOT yet confirmed against this character\'s own melee/spell crit sheet split (no character-sheet screenshot available), so treat as suggestive, not settled - same caveat already on record for Titanic Mutilate\'s first crit data. SOURCE: 2026-08-03 combat log, character Pumprat, Uldaman.', 'Scouting', '2026-08-03 session (Pumprat log)'),
    ('voidbound_lightbound_cleave_dbc_formula', 'Voidbound Cleave (907280) and Lightbound Cleave (907300) share BYTE-IDENTICAL raw DBC EffectBasePoints/EffectBonusCoefficient values. Effect[0] (the tooltip\'s "$s1" bonus term, per "does your weapon damage plus $s1"): EffectBasePoints=8->9 (basepoints+1), EffectDieSides=1, EffectBonusCoefficient=1.0 - a full 1:1 AP-scaling coefficient, notably stronger than any other per-hit coefficient logged in this project (typical range 0.05-0.3). Effect[1] (the "your weapon damage" term): EffectBasePoints=64->65, EffectBonusCoefficient=0.0 - read as ~65% weapon damage, no AP/SP scaling. EffectChainTargets=2 matches "two nearest allies" cleave. CONFIDENCE NOTE: the raw Effect type codes (58, 31) were not matched against a verified SPELL_EFFECT enum table - the bonus-vs-weapon-damage split is inferred from which term carries a nonzero EffectBonusCoefficient paired against the tooltip\'s two-clause wording, not from a named enum lookup. Formula: bonus = 9+AP*1.0, weapon_component = weapon_dmg*0.65. Corrects the Paladin build\'s prior "LC flat 62" assumption, which had no DBC or live-tooltip source found this session. SOURCE: 2026-08-03 Pumprat scouting session, dbc-extract.json.', 'DBC pull', '2026-08-03 session (Pumprat log)'),
    ('improved_cleave_true_magnitude', 'Improved Cleave\'s real per-rank magnitude, confirmed via raw DBC across all 3 ranks (basepoints+1 convention): Rank 1 (12329) EffectBasePoints=39->40%, Rank 2 (12950) EffectBasePoints=79->80%, Rank 3 (20496) EffectBasePoints=119->120%. Clean linear +40%/rank. Tooltip: "Increases the bonus damage done by your Cleave ability by $s1%." Applies to the whole Cleave-modifier-bucket family via the class-tag rule (primer §4) - any card whose tooltip states "uses Cleave modifiers" (Lightbound/Voidbound/Spellbound/Flamebound/Frostbound/Stormbound Cleave, base Cleave itself) should inherit this. At 3/3, applied to the AP-scaling bonus term only (voidbound_lightbound_cleave_dbc_formula): bonus becomes (9+AP)*2.2. CONSEQUENCE: build_paladin-hammerdin.md v8 §7 had ranked Improved Cleave dead-last on the chase list assuming a small flat-and-decaying value - corrected to a much higher priority in v9. SOURCE: 2026-08-03 Pumprat scouting session, dbc-extract.json.', 'DBC pull', '2026-08-03 session (Pumprat log)'),
    ('voidbound_cleave_damage_share_and_parse', 'Voidbound Cleave was 47.7% of Pumprat\'s total logged damage in the 2026-08-03 Uldaman log (1,986,118 of 4,165,003 total across all sources, 826 hits, 60.65% crit) - the single dominant damage source by a wide margin (next: Fel Infused Attack 12.9%). Non-crit hits averaged 1,425 (range 833-2,027), crit hits averaged 3,040 (ratio 2.13x, consistent with a standard physical crit multiplier). Fits the (9+AP)*2.2 + weapon_dmg*0.65 formula in shape for a plausible dungeon-tier AP, though Pumprat\'s actual AP/SP was never captured (no character sheet) so this is not an exact numeric confirmation. See builds/shared/scouted_Pumprat_2026-08-03.md for full derivation and open questions.', 'Scouting', '2026-08-03 session (Pumprat log)'),
    ('paladin_chase_ability_magnitudes_dbc', 'DBC magnitudes resolved for six §8 chase-list abilities (build_paladin-hammerdin.md v10), all via dbc-extract.json spell_dbc_raw + dbc_spellduration: Divine Storm (53385) = 110% weapon damage to multiple enemies + heal-on-hit (EffectBasePoints 109->110); sanity-checked against Elric\'s own Dawn Strike average (812/hit) - at ~723 avg weapon dmg self-buffed, 110% predicts ~795/hit, same order of magnitude. Avenging Wrath (31884) = +20% all damage/healing, 20000ms/20s duration (DurationIndex 18). Guardian of Ancient Kings (277875) = +15% Holy damage (EffectBasePoints[1] 14->15), 12000ms/12s duration (DurationIndex 29), plus resets/discounts Hammer of the Righteous/Divine Storm/Holy Shock cooldowns - the reset effect is not captured by the flat %. Twisted Mind (284448) = flat +60 Spell Power ($PL*1 = player level x1 = 60 at level 60, NOT a percentage), +3% hit (near-worthless per existing hit walkback), healing/absorb reduction magnitude itself hidden behind a second sub-spell (978705) not in this extract; also bar-changing/stance-type, check for conflicts before slotting. Divine Protection (498) = -50% damage taken (EffectBasePoints[1] -51->-50), 12000ms/12s duration (DurationIndex 29), shares a cooldown-exclusion window with Avenging Wrath - defensive only, not a DPS card. Bloodlust (2825) = +30% melee/ranged attack speed + +20% casting speed (EffectBasePoints index2 29->30, index0 19->20), 40000ms/40s duration (DurationIndex 64). Execution Sentence (954817) remains UNRESOLVED even via DBC - all three EffectBasePoints are the -1 "no value" sentinel and EffectTriggerSpell is empty, meaning its real formula is not captured anywhere in this extract (likely hardcoded script logic) - needs a live tooltip, not further DBC digging. IMPORTANT CAVEAT: none of these spells\' actual COOLDOWNS were resolved - this extract has no SpellCooldowns.dbc-equivalent table, only durations. Any "average uptime" DPS estimate built on these numbers is assuming a cooldown value, not measuring one. SOURCE: 2026-08-03 session, dbc-extract.json.', 'DBC pull', '2026-08-03 session'),
    ('method_dps_extrapolation_from_talent_stack', 'Reusable method for projecting a DPS ceiling from a chase list: multiply confirmed per-card %-multipliers MULTIPLICATIVELY, not additively (an older Paladin-build estimate summed them to "~40%" - the correct multiplicative stack for the same four cards is +33.5%, not meaningfully different here but diverges more as more cards stack). For an ability-specific formula change (e.g. Improved Cleave\'s AP-scaling bonus term), compute the per-hit delta directly from the DBC coefficients, propagate through the ability\'s own crit ratio and hit-count share from a real parse, then express as a % of TOTAL logged damage - this avoids needing to separate out the ability\'s weapon-damage component, since only the changed term needs isolating. Always log which stats (AP/SP/crit) the projection was computed FROM, since these decay fast as gear changes - the numbers are a snapshot, the method is what is reusable. Applied 2026-08-03 to build_paladin-hammerdin.md §10a (Improved Cleave + four chase talents -> ~48% ceiling from AP 584/self-buffed sheet).', 'Primer', '§5 (v10)'),
    ('pumprat_demon_package_inconclusive', 'Pumprat\'s active spec (5) carries Summon Felguard + Soul Link + Demonic Tactics 5/5 + Demonic Pact 5/5, but the 2026-08-03 Uldaman log does not meaningfully test the demon package: the summoned pet ("Wrathguard" per this server\'s Summon Felguard flavor, not literally named Felguard) landed only 4 melee swings total in the whole log - functionally idle/not the active pull\'s focus. The "Wild Imp"/"Demonic Persistence"/"Firebolt (Wild Imp)" entries in the same log (481+60 hits) belong to a DIFFERENT player, Oxete (via Hand of Gul\'dan, spellId 954611) - confirmed by SPELL_SUMMON source GUID, do not attribute to Pumprat. Demon-package questions remain open pending a log where the pet is actually active/tanking.', 'Scouting', '2026-08-03 session (Pumprat log)'),
    ('pumprat_inspect_unresolved_talent_ids', 'decode_inspect_export.py run against a live inspect (Pumprat, Darkmoon, Wildcard, spec 5) left 3 talent IDs unresolved against spell-export.json; resolved via dbc-extract.json spell_dbc_raw + dbc_talent. #12855 = Cruelty Rank 4 (direct ID hit in spell_dbc_raw - a genuine rank of Cruelty distinct from both ±3 candidates offered, #12856 Cruelty R5 and #12857 Commanding Presence R2; catalog just does not carry this particular rank). #13806 = Close Quarters Combat Rank 4 (same pattern - direct hit, not Close Quarters Combat R5/Mace Specialization R5/Frost Trap). #15259 = Darkness Rank 1, a Priest Shadow-tree talent (TalentTab id 203): not present in spell_dbc_raw itself (outside the extract\'s scoped ID set, no catalog/hidden_refs neighbor within ±3), found instead via dbc_talent.SpellRank array (talent id 462: ranks [15259, 15307, 15308, 0, 0]) - ranks 2/3 (15307, 15308) ARE in spell_dbc_raw as "Darkness Rank 2/3", confirming the name. Ascension\'s Darkness tooltip reads "Increases all damage done by $s2%. Increases your Shadow damage done by $s2%" - broader than vanilla\'s shadow-only version, consistent with primer §1 (v7) "hybrid/dual scaling turns up in unexpected places, check raw tooltips" pattern. Extends method_rank_id_decoding (primer §5 v8): when a rank ID falls outside spell_dbc_raw\'s scope entirely, check dbc_talent\'s SpellRank arrays for the ID before concluding it is unresolvable - sibling ranks already in scope confirm the name without needing a wider DBC re-extract.', 'DBC pull', '2026-08-03 session (inspect: Pumprat)'),
]

cur.executemany('INSERT INTO confirmed_facts (topic, fact, source_doc, source_section) VALUES (?,?,?,?)',
                 [(t, f, d, s) for (t, f, d, s) in FACTS])

conn.commit()
cur.execute('SELECT COUNT(*) FROM spells WHERE class_origin IS NOT NULL')
print('spells with confirmed class_origin:', cur.fetchone()[0])
cur.execute('SELECT COUNT(*) FROM confirmed_facts')
print('confirmed_facts rows:', cur.fetchone()[0])
conn.close()
