"""Repo-relative path resolution — the ONE place a filesystem layout is written down.

ARCHITECTURE §2.7 rule 1: `core/` has no hardcoded paths and takes a connection as a
parameter. So **`core/` must never import this module.** Only `ingest/`, `cli/`,
`tools/` and `api/` do — they are the layers allowed to know where files live.

Every path here is derived from this file's own location, so a fresh clone works
anywhere with no environment setup.
"""
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent

# --- source data: committed, hand-or-crawler-captured, never regenerated by us ---
DATA_SOURCE = REPO / "data" / "source"
EXPORT_DIR = DATA_SOURCE / "export"          # spell-export.json, Cards.txt
DBC_DIR = DATA_SOURCE / "dbc"                # dbc-extract.json, dbc-ascension-extract.json
SCOUTED_DIR = DATA_SOURCE / "scouted"        # scouted_<name>_<date>.json
CHANGELOG_DIR = DATA_SOURCE / "changelog"    # daily/ + backfill/ page captures
CRAWL_DIR = DATA_SOURCE / "crawl"            # per-day crawler output

SPELL_EXPORT = EXPORT_DIR / "spell-export.json"
CARDS_FILE = EXPORT_DIR / "Cards.txt"
DBC_EXTRACT_JSON = DBC_DIR / "dbc-extract.json"
DBC_ASCENSION_EXTRACT_JSON = DBC_DIR / "dbc-ascension-extract.json"

# --- derived: gitignored, always rebuildable from the above (§2.12) ---
DATA_DERIVED = REPO / "data" / "derived"
DB_PATH = DATA_DERIVED / "ascension.db"              # the one Phase 1 database
SCOUTED_DB_PATH = DATA_DERIVED / "scouted_builds.db"  # separate until Phase 3 folds it in

# --- docs ---
PRIMER_DIR = REPO / "primer"
BUILDS_DIR = REPO / "builds"


def ensure_derived_dir() -> Path:
    """Create data/derived/ if absent. Callers write .db files into it."""
    DATA_DERIVED.mkdir(parents=True, exist_ok=True)
    return DATA_DERIVED


def ensure_utf8_stdout() -> None:
    """Make stdout/stderr UTF-8 so piped output does not crash on Windows.

    Python picks the console codepage (cp1252 here) for a NON-CONSOLE stdout, so
    any script that prints ⚠ or 🛑 dies with UnicodeEncodeError the moment its
    output is piped or redirected — while working perfectly in a terminal. That
    is the worst possible failure shape: it only appears when someone captures
    the output, which is exactly when they are least able to see why.

    Flagged in INDEX_GUIDE v10 against `build_index.py` and left unfixed since;
    it recurred in 2c against `seed_epistemics.py`. Call this once at the top of
    any entry point that prints non-ASCII. Idempotent, and a no-op on a stream
    that does not support reconfigure.
    """
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass
