"""Phase 2 T5 — default APL generation.

Produces a priority list from a BuildSpec so builds can be compared without
hand-authoring a rotation for each one, and so the guide generator has a
rotation section to render (PHASE_2 T5).

Priority rules, in order:
  1. cooldown abilities first, longest cooldown first — a long cooldown that
     slips is unrecoverable, a filler that slips costs one GCD;
  2. then by damage per GCD;
  3. quadratic combo-point finishers gated at MAX combo points — the primer's
     "never dump below max CP" rule is structural, not a preference: going 3->5
     CP is ~2.8x, not 1.67x;
  4. self-sustain abilities gated on health when the content profile requires
     it — a solo build that never heals is not the build being evaluated;
  5. off-GCD abilities are marked as such so they are queued alongside, not
     instead of, a GCD action.

⚠ This is "good enough to compare builds", not an optimiser. It does not search
orderings, and a hand-authored APL will usually beat it.
"""
from .ability_model import resolve_ability, AbilityResolutionError
from .apl import APL, APLEntry

MAX_COMBO_POINTS = 5
SELF_SUSTAIN_HEALTH_PCT = 50.0


def generate_apl(conn, build_spec, content, char_state, name=None):
    """Build a default APL. Abilities the resolver refuses are omitted AND
    named in the APL's provenance — a silently dropped ability would change the
    rotation without saying so."""
    scored, refused = [], []
    for card in build_spec.abilities:
        try:
            ab = resolve_ability(conn, card.spell_id,
                                 level=build_spec.character_level)
        except AbilityResolutionError as e:
            refused.append(f"{card.spell_id} ({e})")
            continue
        exp = ab.expected_cast(char_state, content)
        if exp.mean <= 0 and not exp.unresolved_events:
            continue                      # no damage: not a rotational button
        cd = ab.fields.get("cooldown_seconds") or 0.0
        gt = ab.fields.get("gcd_type")
        off_gcd = gt in ("none", "off")
        scored.append({
            "ability": ab, "spell_id": ab.spell_id, "cooldown": cd,
            "off_gcd": off_gcd, "mean": exp.mean,
            "is_finisher": any(
                t.get("cp_scaling") for t in ab.damage_terms),
            "is_quadratic": any(
                t.get("cp_scaling") == "quadratic" for t in ab.damage_terms),
            "heals": exp.mean_healing > 0,
        })

    # off-GCD first (they cost nothing to queue), then cooldowns longest-first,
    # then fillers by damage
    off = [s for s in scored if s["off_gcd"]]
    cds = sorted([s for s in scored if not s["off_gcd"] and s["cooldown"] > 0],
                 key=lambda s: -s["cooldown"])
    fillers = sorted([s for s in scored if not s["off_gcd"] and not s["cooldown"]],
                     key=lambda s: -s["mean"])

    entries = []
    for s in off:
        entries.append(APLEntry(
            spell_id=s["spell_id"], conditions=[{"type": "always"}],
            off_gcd=True,
            comment=f"{s['ability'].name}: off-GCD, queue alongside a GCD action"))

    if content.self_sustain_required:
        for s in scored:
            if s["heals"] and not s["off_gcd"]:
                entries.append(APLEntry(
                    spell_id=s["spell_id"],
                    conditions=[{"type": "health_pct_below",
                                 "value": SELF_SUSTAIN_HEALTH_PCT}],
                    comment=f"{s['ability'].name}: self-sustain, gated on health "
                            "because this content profile requires it"))

    for s in cds:
        entries.append(APLEntry(
            spell_id=s["spell_id"], conditions=[{"type": "always"}],
            comment=f"{s['ability'].name}: on cooldown ({s['cooldown']:g}s)"))

    for s in fillers:
        conds = [{"type": "always"}]
        comment = f"{s['ability'].name}: filler"
        if s["is_finisher"]:
            conds = [{"type": "combo_points_at_least",
                      "value": MAX_COMBO_POINTS}]
            comment = (f"{s['ability'].name}: finisher held to "
                       f"{MAX_COMBO_POINTS} CP")
            if s["is_quadratic"]:
                comment += " — QUADRATIC CP scaling, never dump below max"
        entries.append(APLEntry(spell_id=s["spell_id"], conditions=conds,
                                comment=comment))

    prov = (f"auto-generated by apl_gen for content={content.name}; "
            f"{len(entries)} entries")
    if refused:
        prov += f". OMITTED (resolver refused): {'; '.join(refused)}"
    return APL(name=name or f"auto_{content.name}", entries=entries,
               provenance=prov)
