"""
Decoder for AscensionLogsCompanion's [[ALC_F_v1_c2_...]] payloads embedded
in WoWCombatLog.txt SPELL_CAST_FAILED fail-reason fields.

Pipeline (reverse of Capture/FrameBuilder.lua + Core/Serialize.lua):
    chunks -> reassemble by (session,frame) -> custom base64 decode
    -> raw DEFLATE decompress w/ D1 preset dictionary -> Frame demux
    -> AceSerializer-3.0 deserialize each record body -> Python dict/list

Verified against a real payload generated by the addon's own vendored
libs (LibStub/AceSerializer-3.0/LibDeflate) via a Lua harness -- not a
guessed format. See harness.lua / harness_output.txt for the ground truth
this was checked against.
"""

import re
import zlib
from pathlib import Path

# ---------------------------------------------------------------------------
# 1. Custom base64 (Core/Base64.lua): alphabet A-Za-z0-9-_ , '.' as padding
# ---------------------------------------------------------------------------
_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
_DECODE_MAP = {ch: i for i, ch in enumerate(_ALPHABET)}


def alc_base64_decode(s: str) -> bytes:
    if len(s) % 4 != 0:
        raise ValueError(f"ALC base64 length not a multiple of 4: {len(s)}")
    out = bytearray()
    for i in range(0, len(s), 4):
        group = s[i:i + 4]
        pad = group.count(".")
        vals = [0 if c == "." else _DECODE_MAP[c] for c in group]
        n = vals[0] * 262144 + vals[1] * 4096 + vals[2] * 64 + vals[3]
        b1 = (n >> 16) & 0xFF
        b2 = (n >> 8) & 0xFF
        b3 = n & 0xFF
        if pad == 0:
            out += bytes((b1, b2, b3))
        elif pad == 1:
            out += bytes((b1, b2))
        elif pad == 2:
            out += bytes((b1,))
        else:
            raise ValueError(f"ALC base64: invalid padding count {pad} in group {group!r}")
    return bytes(out)


# ---------------------------------------------------------------------------
# 2. Raw DEFLATE decompress w/ D1 preset dictionary (Core/DictD1.lua)
# ---------------------------------------------------------------------------
_D1_PATH = Path(__file__).parent / "d1_dict.bin"


def load_d1_dict() -> bytes:
    return _D1_PATH.read_bytes()


def deflate_with_dict_decompress(data: bytes, dictionary: bytes) -> bytes:
    # LibDeflate's CompressDeflate* family produces a raw DEFLATE stream
    # (no zlib/gzip header) -> wbits=-15. zdict supplies the preset dictionary.
    d = zlib.decompressobj(wbits=-15, zdict=dictionary)
    out = d.decompress(data)
    out += d.flush()
    return out


# ---------------------------------------------------------------------------
# 3. Frame demux (Core/Frame.lua): MAGIC 0xA1 VER 0x01 (type:u8 uvarint body)*
# ---------------------------------------------------------------------------
FRAME_MAGIC = 0xA1
FRAME_VERSION = 0x01
RECORD_TYPES = {0x01: "CI", 0x02: "PP", 0x03: "TS", 0x04: "KS", 0x12: "KEYFRAME_REF"}


def _read_uvarint(buf: bytes, pos: int):
    result = 0
    shift = 0
    while True:
        b = buf[pos]
        pos += 1
        result |= (b & 0x7F) << shift
        if b < 0x80:
            break
        shift += 7
    return result, pos


def decode_frame(buf: bytes):
    if len(buf) < 2 or buf[0] != FRAME_MAGIC or buf[1] != FRAME_VERSION:
        raise ValueError(f"Bad frame header: {buf[:2].hex() if len(buf) >= 2 else buf.hex()}")
    pos = 2
    records = []
    while pos < len(buf):
        rtype = buf[pos]
        pos += 1
        length, pos = _read_uvarint(buf, pos)
        body = buf[pos:pos + length]
        pos += length
        records.append((RECORD_TYPES.get(rtype, f"UNKNOWN_0x{rtype:02x}"), body))
    return records


# ---------------------------------------------------------------------------
# 4. AceSerializer-3.0 deserialize (exact port of AceSerializer-3.0.lua)
# ---------------------------------------------------------------------------
_STR_UNESCAPE = {
    "~z": "\x1e",   # ticket 115 special case (30 + 64 = 94 collision)
    "~{": "\x7f",
    "~|": "~",
    "~}": "^",
}


def _unescape_string(data: str) -> str:
    def repl(m):
        esc = m.group(0)
        if esc in _STR_UNESCAPE:
            return _STR_UNESCAPE[esc]
        # ~X -> chr(byte(X) - 64) for the generic nonprint+space case
        return chr(ord(esc[1]) - 64)
    return re.sub(r"~.", repl, data)


class _TokenIter:
    """Mirrors gmatch(str, "(^.)([^^]*)") over the AceSerializer stream."""

    def __init__(self, s: str):
        self._tokens = re.findall(r"(\^.)([^^]*)", s)
        self._i = 0

    def next(self):
        if self._i >= len(self._tokens):
            return None, None
        tok = self._tokens[self._i]
        self._i += 1
        return tok


def _deserialize_value(it: _TokenIter, single=False, ctl=None, data=None):
    if not single:
        ctl, data = it.next()
    if ctl is None:
        raise ValueError("AceSerializer stream missing terminator ('^^')")
    if ctl == "^^":
        return None

    if ctl == "^S":
        res = _unescape_string(data)
    elif ctl == "^N":
        if data == "nan":
            res = float("nan")
        elif data == "inf":
            res = float("inf")
        elif data == "-inf":
            res = float("-inf")
        else:
            res = float(data) if any(c in data for c in ".eE") else int(data)
    elif ctl == "^F":
        ctl2, e_str = it.next()
        if ctl2 != "^f":
            raise ValueError(f"Expected '^f' after '^F', got {ctl2!r}")
        m = float(data)
        e = float(e_str)
        res = m * (2 ** e)
    elif ctl == "^B":
        res = True
    elif ctl == "^b":
        res = False
    elif ctl == "^Z":
        res = None
    elif ctl == "^T":
        res = {}
        arr_probe = []  # track if keys are a clean 1..N int sequence -> emit as list
        while True:
            ctl2, data2 = it.next()
            if ctl2 == "^t":
                break
            k = _deserialize_value(it, True, ctl2, data2)
            ctl3, data3 = it.next()
            v = _deserialize_value(it, True, ctl3, data3)
            res[k] = v
        # Convenience: if keys are exactly 1..N (Lua array-style), return a list
        keys = list(res.keys())
        if keys and all(isinstance(k, int) for k in keys) and sorted(keys) == list(range(1, len(keys) + 1)):
            res = [res[i] for i in range(1, len(keys) + 1)]
    else:
        raise ValueError(f"Unknown AceSerializer control code {ctl!r}")

    return res


def ace_deserialize(s: str):
    """
    Returns the deserialized value. ALC always calls Serialize() with a
    single argument (the CI/TS/PP/etc struct), so this returns that one
    value rather than reproducing AceSerializer's general multi-return
    semantics (which only matter for multi-arg Serialize() calls).
    """
    s = re.sub(r"[\x00-\x1f ]", "", s)  # strip control chars + spaces, per lib
    if not s.startswith("^1"):
        raise ValueError("Not AceSerializer rev-1 data (missing '^1' header)")
    it = _TokenIter(s[2:])
    ctl, data = it.next()
    return _deserialize_value(it, single=True, ctl=ctl, data=data)


# ---------------------------------------------------------------------------
# End-to-end: chunk sentinel -> reassembled records
# ---------------------------------------------------------------------------
CHUNK_RE = re.compile(r"\[\[ALC_F_v1_c2_([^_]+)_([^_]+)_(\d+)/(\d+)\]\](.*)")


def decode_chunks(chunk_lines, dictionary: bytes = None):
    """
    chunk_lines: iterable of raw strings, each containing one [[ALC_F_v1_c2_...]] token
                 (may have other combat-log text around it -- we regex-extract).
    Returns: list of (record_type, deserialized_value) across all frames found.
    """
    if dictionary is None:
        dictionary = load_d1_dict()

    frames = {}  # (session, frame_id) -> {seq: payload}
    totals = {}
    for line in chunk_lines:
        m = CHUNK_RE.search(line)
        if not m:
            continue
        session, frame_id, seq, total, payload = m.groups()
        # The combat log wraps each chunk in a quoted CSV field; our capture
        # (`.*` to end of line) picks up that field's closing '"', which is
        # not part of the base64 payload and throws off the group-of-4 length.
        payload = payload.rstrip('"')
        key = (session, frame_id)
        frames.setdefault(key, {})[int(seq)] = payload
        totals[key] = int(total)

    results = []
    for key, parts in frames.items():
        total = totals[key]
        if len(parts) != total:
            missing = sorted(set(range(1, total + 1)) - set(parts))
            print(f"[warn] frame {key} incomplete: have {len(parts)}/{total}, missing seq {missing} -- skipping")
            continue
        b64 = "".join(parts[i] for i in range(1, total + 1))
        try:
            compressed = alc_base64_decode(b64)
            raw_frame = deflate_with_dict_decompress(compressed, dictionary)
            frame_records = decode_frame(raw_frame)
        except Exception as e:
            print(f"[warn] frame {key} failed to decode ({e}) -- skipping")
            continue
        for rtype, body in frame_records:
            try:
                value = ace_deserialize(body.decode("utf-8", errors="strict"))
            except Exception as e:
                print(f"[warn] failed to deserialize {rtype} record in frame {key}: {e}")
                continue
            results.append((rtype, value))
    return results


if __name__ == "__main__":
    import sys
    import pprint

    log_path = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    if log_path:
        lines = log_path.read_text(errors="ignore").splitlines()
    else:
        lines = sys.stdin.read().splitlines()

    for rtype, value in decode_chunks(lines):
        print(f"--- {rtype} ---")
        pprint.pprint(value)
