#!/usr/bin/env python3
"""Pre-classify the 'needs manual review' talent_amplifiers rows (session 1c).

Owner decision 2026-08-05: **pre-classify with evidence into a review file;
NOTHING enters `spell_relationships` until the owner approves a batch.** This
script writes `reviews/amplifier_review.md` — a committed, human-editable queue
— and touches no graph table.

Pre-classification (a proposal, not a verdict — the evidence is right next to
each row so the owner can overrule at a glance):

* `verbatim_ability` — target text contains a catalog spell name. These were
  misfiled as school_generic by the v3 bulk scan; primer §5 says verbatim names
  are the HIGH-confidence tier. Proposed edge: `amplifies` → the named spell(s).
* `school_amplifier` — target names a school + spells/damage wording. Proposed
  edge: `amplifies_school` (enters at low confidence, proc-test flagged).
* `stat_or_defense` — targets a stat/defense channel (crit chance, dodge,
  armor, Intellect…), not a spell's damage. Proposed action: EXCLUDE from the
  relationship graph — these belong to Phase 2's stat modelling, and wiring
  them as damage amplifiers would be wrong, not just noisy.
* `unclassified` — none of the above matched; needs a real human read.

Approval contract (for the future ingester — do not build it before a batch is
actually approved): flipping a row's `[ ]` to `[x]` approves the PROPOSED
action; writing `[!]` rejects it with a note after the row.
"""
import re
import sqlite3
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from config import DB_PATH  # noqa: E402

OUT = REPO / "reviews" / "amplifier_review.md"

SCHOOLS = ("Fire", "Frost", "Shadow", "Arcane", "Nature", "Holy", "Physical",
           "Holystrike", "Holyfire", "Shadowflame", "Firestrike", "Froststrike",
           "Shadowstrike", "Spellstrike", "Stormstrike")

STAT_PAT = re.compile(
    r"critical strike|crit chance|hit chance|dodge|parry|block|armor|"
    r"intellect|stamina|spirit|strength|agility|attack power|spell power|"
    r"haste|resistance|healing (received|done|taken)|movement speed|"
    r"mana (cost|regen)|rage|energy|threat|expertise|health|resilience|"
    r"chance to (hit|resist)|penetration|damage taken|absorb", re.I)


def classify(target, spell_names_longest_first, name_pats):
    named = [n for n in spell_names_longest_first if name_pats[n].search(target)]
    if named:
        # mask shorter names inside longer matches (Righteous Vengeance ⊃ Vengeance)
        keep, masked = [], target
        for n in named:
            if name_pats[n].search(masked):
                keep.append(n)
                masked = name_pats[n].sub(" " * len(n), masked)
        if keep:
            # a named ability + stat wording is usually "a stat while/using X",
            # not "X's damage" — keep the verbatim proposal but flag it so the
            # reviewer checks which thing is actually being amplified
            flag = bool(STAT_PAT.search(target))
            return ("verbatim_ability_check_stat" if flag
                    else "verbatim_ability"), keep
    school_hit = [s for s in SCHOOLS
                  if re.search(rf"\b{s}\b.{{0,20}}(spell|damage|abilit)", target, re.I)
                  or re.search(rf"(spell|damage|abilit).{{0,20}}\b{s}\b", target, re.I)]
    if school_hit:
        return "school_amplifier", school_hit
    if STAT_PAT.search(target):
        return "stat_or_defense", []
    return "unclassified", []


def main():
    conn = sqlite3.connect(str(DB_PATH))
    names = {}
    for sid, name in conn.execute(
            "SELECT id, name FROM spells WHERE name IS NOT NULL AND length(name) >= 4"):
        names.setdefault(name, []).append(sid)
    longest_first = sorted(names, key=len, reverse=True)
    name_pats = {n: re.compile(r"\b" + re.escape(n) + r"\b", re.I)
                 for n in longest_first}

    rows = conn.execute("""
        SELECT ta.talent_spell_id, s.name, ta.target_effect,
               replace(substr(s.tooltip, 1, 220), char(13), ' ')
        FROM talent_amplifiers ta JOIN spells s ON s.id = ta.talent_spell_id
        WHERE ta.notes LIKE '%manual review%'
        ORDER BY s.name""").fetchall()

    groups = {"verbatim_ability": [], "verbatim_ability_check_stat": [],
              "school_amplifier": [], "stat_or_defense": [], "unclassified": []}
    for tid, tname, target, tooltip in rows:
        kind, hits = classify(target or "", longest_first, name_pats)
        groups[kind].append((tid, tname, target, tooltip, hits))

    OUT.parent.mkdir(exist_ok=True)
    L = ["# Amplifier review queue — pre-classified, awaiting owner approval",
         "",
         "Generated by `tools/audit/build_amplifier_review.py` from the "
         f"{len(rows)} `talent_amplifiers` rows flagged 'needs manual review'.",
         "",
         "**Owner decision 2026-08-05: nothing below enters `spell_relationships` "
         "until a batch is approved here.** `[x]` approves the proposed action, "
         "`[!]` rejects (add a note on the next line). Regenerating this file "
         "preserves nothing — approve in git, not in a throwaway copy.",
         ""]
    blurb = {
        "verbatim_ability": "Target text names a catalog spell verbatim — the "
            "HIGH-confidence tier (primer §5). Proposed: `amplifies` edge(s) to "
            "the named spell(s). ⚠ names resolve to IDs at ingest time via the "
            "duplicate-name discipline, never blindly.",
        "verbatim_ability_check_stat": "Names a catalog spell BUT also matches "
            "stat wording — usually 'a stat while/using X', not 'X's damage'. "
            "Proposed: `amplifies` edge, but CHECK which thing is amplified "
            "before approving.",
        "school_amplifier": "Target names a school — proposed: `amplifies_school` "
            "edge at low confidence, proc-test flagged (generic wording).",
        "stat_or_defense": "Targets a stat/defense channel, not a spell's damage. "
            "Proposed: EXCLUDE from the relationship graph (Phase 2 stat "
            "modelling owns these). Approving confirms the exclusion.",
        "unclassified": "No pattern matched — needs a real human read before any "
            "proposal can be made.",
    }
    for kind in ("verbatim_ability", "verbatim_ability_check_stat",
                 "school_amplifier", "stat_or_defense", "unclassified"):
        rows_k = groups[kind]
        L += [f"## {kind} — {len(rows_k)} row(s)", "", blurb[kind], ""]
        for tid, tname, target, tooltip, hits in rows_k:
            hit_txt = f" → **{', '.join(str(h) for h in hits)}**" if hits else ""
            L.append(f"- [ ] `{tid}` **{tname}** — target: “{target}”{hit_txt}")
            L.append(f"      evidence: `{tooltip.strip()}`")
        L.append("")
    OUT.write_text("\n".join(L), encoding="utf-8")

    counts = {k: len(v) for k, v in groups.items()}
    print(f"amplifier review queue written: {OUT}")
    print(f"  {counts}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
