#!/usr/bin/env python3
"""Seeds class_origin / best_fit_path / confirmed_facts strictly from statements
already made in Ascension_Context_Primer.md and Ascension_Paladin_Handoff.md.
Nothing here is guessed — every row traces to a doc + section."""
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).resolve().parent.parent / 'data' / 'ascension_index.db'
conn = sqlite3.connect(str(DB_PATH))
cur = conn.cursor()

# (spell_id, class_origin, confidence, note)
CLASS_ORIGIN = [
    (903158, 'Paladin', 'confirmed_class_tag_rule', 'Borrows Crusader Strike modifiers; feeds Hammerdin. Primer §4 / Handoff §2.'),
    (907894, 'Rogue',   'predicted_class_tag_rule', 'Borrows Sinister Strike modifiers; does NOT feed Hammerdin proc. Primer §4.'),
    (904880, 'Rogue',   'predicted_class_tag_rule', 'Borrows Eviscerate modifiers; does NOT feed Hammerdin proc. Primer §4.'),
    (907300, 'Warrior', 'confirmed_proc_test',      'Borrows Cleave modifiers. CONFIRMED zero procs from "damaging Paladin abilities" trigger. Primer §4 / Handoff §2.'),
    (907780, 'Warrior', 'predicted_class_tag_rule', 'Borrows Whirlwind modifiers; does NOT feed Hammerdin proc. Primer §4.'),
    (913444, 'Warrior', 'confirmed_class_tag_rule', 'Borrows Bladestorm modifiers; does NOT feed Hammerdin. Also a channelled lockout ability - suppresses narrow-intake engines while active. Primer §4 / Handoff §2.'),
    (20473,  'Paladin', 'confirmed_native',         'Native Paladin ability. Handoff §2.'),
    (280210, 'Physical', 'confirmed_native',        'Judgement of the Three Hammers - triggered by "any direct damage" (wide intake), crits on Physical/melee table. Handoff §4/§9.'),
    (26573,  'Paladin', 'confirmed_native',         'Native Paladin ability (Consecration). Handoff §12 - "Consecration earns its slot" (v4 verdict overturned).'),
    (853486, 'Paladin', 'confirmed_native',         'The Art of War - Handoff §12, v4 "dead" verdict overturned (cut on wrong tooltip clause).'),
    (282984, 'Paladin', 'confirmed_native',         'Hour of Judgement - core Paladin cooldown, triggers hidden sub-spell "Hammer from the Heavens" (282987, not in catalog export). Handoff §1/§4/§12.'),
    (276076, 'Duality', 'confirmed_native',         'Fel Infused Weapon - hybrid AP*0.05+SP*0.05+flat Shadowflame proc, no ICD in tooltip, fires on every auto attack AND melee ability. Primer §1 (v6).'),
    (272624, 'Shaman',  'confirmed_class_tag_rule', 'Molten Earth - live tooltip confirms "uses Fire Nova modifiers". Triggered by Lava Lash (Shaman) but NOT modified by Lava Lash talents (Elemental Fusion, Lava Flows) - class-tag rule proof case #2, Primer §4. Formula: 60+(SP+AP)*0.12 Fire dmg/tick, 8 ticks.'),
]

BEST_FIT_PATH = [
    (903158, 'Duality', 'Physical+Holy hybrid via Crusader Strike base - benefits from AP and Holy SP exposure. Inferred from build context, not an explicit path statement.'),
    (272624, 'Duality', 'Pure Fire school but carries both SP*0.12 and AP*0.12 per-tick coefficients - hybrid AP+SP scaling is not exclusive to named -strike schools (Primer §1, v7). Benefits from Duality itemization despite not being a hybrid-named school.'),
]

cur.executemany('''UPDATE spells SET class_origin=?, class_confidence=?, notes=?
                    WHERE id=?''',
                 [(co, conf, note, sid) for (sid, co, conf, note) in CLASS_ORIGIN])

for sid, path, note in BEST_FIT_PATH:
    cur.execute('UPDATE spells SET best_fit_path=?, notes=COALESCE(notes,"")||? WHERE id=?',
                (path, ' | PATH: ' + note, sid))

FACTS = [
    ('crit_conversion', 'Crit rating: 14.0 rating per 1%, identical melee and spell (measured: 393->28.07%, 164->11.71%).', 'Primer', '§1'),
    ('hit_cap', 'Special-attack (yellow) hit cap vs raid boss: 8%. Dual-wield white attacks carry +19% miss on top - DW auto-attacks can be near-worthless (measured 4.2% of damage).', 'Primer', '§1'),
    ('expertise_cap', 'Expertise dodge cap: 26.', 'Primer', '§1'),
    ('periodic_no_crit', 'Ground/periodic effects generally cannot crit - confirmed repeatedly for aura-tick DoTs (PBL ground 0%/32 ticks; Righteous Vengeance 0% over 4 parses). CONFIRMED EXCEPTION, mechanism theory RETRACTED (v7): Molten Earth live tooltip is a textbook aura-tick DoT ("60+(SP+AP)*0.12 Fire dmg every second for 8 sec, uses Fire Nova modifiers") - structurally identical to Righteous Vengeance - yet parses 40.7% crit over 575 hits vs Righteous Vengeance 0% over 4 parses. The v6 "aura-tick vs instant-pulse ground object" theory does NOT survive this; no structural predictor found. Crit-capability appears to be a per-spell server-side flag. Verify per ability from a parse, never infer from tooltip structure.', 'Primer', '§1'),
    ('fel_infused_weapon_scaling', 'Fel Infused Weapon: guaranteed Shadowflame proc on every auto attack AND melee ability, no ICD stated in tooltip, for [flat + AP*0.05 + SP*0.05]. Scales directly with attack frequency rather than weapon damage - reported up to ~30% of total DPS for hyper-fast dual-wield attackers in group parses. Strong argument for maximizing weapon speed independent of weapon DPS when a build carries this or similar no-ICD per-hit cards. Always check for an ICD before assuming a per-hit proc is diluted by faster/smaller hits.', 'Primer', '§1 (v6)'),
    ('holy_unresistable', 'Holy is unresistable - Spell Penetration worthless against it.', 'Primer', '§1'),
    ('hybrid_school_rule', 'Hybrid abilities (Holystrike, Holyfire, Shadowflame, Firestrike, Froststrike, Shadowstrike, Spellstrike, Stormstrike) have two damage components (physical weapon half + magic school half) and double-dip modifiers from BOTH component schools. They are NOT classified as Spells for gating/trigger purposes even though the magic half exists.', 'Primer', '§1'),
    ('hybrid_crit_table', 'RESOLVED: hybrid strikes (Holystrike) crit on the SPELL table, not melee, and take Holy modifiers. Method: parse crit% per source, sort against sheet melee/spell values. Spell crit rating can be worth several times melee crit rating in a hybrid build.', 'Primer', '§1 / §5', ),
    ('class_tag_rule', "A card's \"uses X modifiers\" line predicts its class tag, NOT its flavour/name/damage school. Confirm with a dummy proc count. sharesModifiersWith opens cross-class talent chase surfaces.", 'Primer', '§4'),
    ('engine_intake', 'Narrow intake (e.g. "damaging Paladin abilities") only accepts same-class-tagged buttons - a build can starve its own engine without noticing. Wide intake (e.g. "dealing direct damage") accepts everything. Always map engine intake against the actual rotation.', 'Primer', '§4'),
    ('channelled_lockout_poison', 'Abilities worded "cannot perform any other abilities" (Bladestorm-family) suppress every narrow-intake proc engine for the whole channel - can show as top damage source in a parse while being net-negative. Compare total damage across rotations, never per-ability shares.', 'Primer', '§4'),
    ('exclusivity_bucket_alldamage', 'Enhanced Weapon Mastery <-> Unending Fury <-> Answered Prayers <-> Blessed Weapons all share an all-damage% "does not stack / highest applies" bucket. Similar wording on Holy Focus and Dual Wield Specialization <-> Dual Wield Mastery (fully redundant, one always dead).', 'Primer', '§2'),
    ('lucky_flag_falsified', 'LUCKY family flag theory FALSIFIED - Divine Steed (no-LUCKY) rolls repeatedly. Working roll model is rarity x affinity only.', 'Primer', '§2'),
    ('duplicate_name_trap', 'Distinct cards can share a name across classes (Vengeance: Paladin r3 stacking-damage vs Druid r5 spell-crit-damage). Ascension can also reuse a retail/classic name for a totally different mechanic - Mental Quickness here is a physical<->magic ping-pong buff, NOT the WotLK AP->SP converter. Always read the actual tooltip; never assume from name.', 'Primer', '§2'),
    ('export_tooltip_incomplete', 'Export tooltips can OMIT entire clauses, not just leave $s1 unresolved. Enhanced Weapon Mastery export reads only the damage% line - the live tooltip adds the exclusivity clause that turns it from top-tier to a dead slot. Get a live tooltip screenshot before any final card verdict.', 'Primer', '§2'),
    ('path_strength', 'Path of Strength: flat Str (4 + 0.5/lvl, ~34@60); AP = 100% of Strength; Str->Parry. 1H: +20% ArP. 2H: melee/ranged physical abilities +10%.', 'Primer', '§3'),
    ('path_agility', 'Path of Agility: flat Agi (same curve); AP = 100% of Agility; Agi->crit chance AND crit damage. 1H: -8% GCD/cost on damaging melee/ranged abilities. 2H: +20% ability crit damage.', 'Primer', '§3'),
    ('path_duality', 'Path of Duality (tooltip claims): AP = highest of Str/Agi; Int->melee/ranged crit; Agi->spell crit; casting no longer resets swing timer. 2H: +6% magic AND physical damage. 1H: +10% haste. v4 SP amp (x1.75) and cross-crit conversion claims RETRACTED - not visible on a live sheet (Handoff §4 URGENT: may not be active at all, verify in-game). Mental Dexterity (talent card) independently implements the same Int->melee crit / Agi->spell crit conversion and can be used regardless of whether the path passive is confirmed live.', 'Primer', '§3 / Handoff §4'),
    ('path_intelligence', 'Path of Intelligence: bonus SP/Int/Spirit (flat Int 4+1.25/lvl ~79@60; Spirit ~40); SP from items/effects DOUBLED. 2H: +12% spell haste. 1H: +5% spell damage.', 'Primer', '§3'),
    ('path_healing', 'Path of Healing: enables Healer role; Healing Power is a distinct gated stat (off-path healing = emergency top-offs only). Flat Int/Spirit like Intelligence path. 2H: +10% spell haste, +3% spell crit. 1H: +5% healing.', 'Primer', '§3'),
    ('path_rules_misc', '"Abilities" wording in path bonuses excludes auto-attacks (yellow only); "Damage done" wording includes autos. Titan\'s Grip/double-2H counts as 2H for path clauses. Path switching is free and instant - always verify active path on the sheet before reasoning from grants.', 'Primer', '§3'),
    ('rv_findings', 'Righteous Vengeance: 30% of crit damage over 8s as Holy DoT. 0% crit across 4 parses (confirms periodic/no-crit rule). 92-101% uptime, pools on refresh (Ignite/Deep Wounds style, does not clip). Measured 6.4-9.0% of total damage. Raises marginal crit value from 2.0x to 2.6x a normal hit.', 'Handoff', '§4'),
    ('paladin_crit_exposure', 'Paladin build v5 crit-table exposure from King Gordok parse: Spell table 70.2%, Melee table 14.3%, Cannot-crit 15.3% (Righteous Vengeance, Holy Vengeance DoT, Hour of Judgement, Consecration).', 'Handoff', '§4/§9'),
    ('paladin_stat_weights', 'Paladin v5 stat weights (combined per-rating value, hit/crit are unified melee+spell on this server): Crit Rating 2.00 (best stat, not close) | Weapon DPS 2.6 | AP 1.00 | Str 1.00 | SP 1.00 (->1.77 if Duality amp restored) | Holy SP 0.95 | Int 0.50 | Haste 0.50 | Hit 0.30 (0.00 for dungeon content, raid only) | Expertise 0.30 (provisional) | Armor Pen 0.18 | Agi 0.15 | Stamina 0.15 | Mana/5 0.10 | Spirit/Spell Pen/Resil 0.00.', 'Handoff', '§10'),
    ('hit_expertise_walkback', 'Crit table and hit table are INDEPENDENT rolls - Holystrike critting on spell table does not mean it rolls spell hit. Only ~5.4% of the Paladin v5 parse damage is confirmed spell-hit-gated (Holy Shock+Judgement). Melee-table hybrid abilities use melee hit (already capped). Periodic effects cannot miss. Procs riding an already-landed attack do not re-roll. Summoned procs (Hammer from the Heavens, JotTH, ~29% of damage) are UNRESOLVED whether they roll a hit check at all - decides whether raid Hit weight is ~0.0 or ~1.2.', 'Handoff', '§10'),
    ('hidden_subspell_hoth', 'Hammer from the Heavens (triggered by Hour of Judgement) has a hidden sub-spell ID 282987 not present in the catalog export - its exact SP/AP/flat composition is UNCONFIRMED, currently assumed 30% SP / 30% AP / 40% flat pending a live tooltip.', 'Handoff', '§10/§12'),
    ('rotation_error', 'Biggest identified free DPS gain (v5): Judgement and Holy Shock were pressed only ~3 times each in a 309s fight vs an expected ~38 and ~50 - starving the Hammerdin engine that brings back Hour of Judgement.', 'Handoff', '§11'),
    ('method_crit_table_id', 'Cheapest mechanics test available: parse crit% per source, sort against the sheet\'s melee and spell crit values in one combat log - immediately reveals which table each ability uses; 0% crit reveals a periodic effect. Settled the Holystrike crit-table question after 2 doc versions "under review". CORRECTION (v7): a nonzero crit% on a periodic/ground effect is NOT reliable evidence it differs structurally from a normal aura tick - Molten Earth is a confirmed aura-tick DoT that still crits. Use crit% to sort spell-vs-melee table, not to infer implementation.', 'Primer', '§5'),
    ('method_sample_size', 'Crit-rate questions need thousands of hits to test; damage-multiplier questions need ~100. If candidate values are within ~3 points, find a different discriminator.', 'Primer', '§5'),
    ('method_no_reroll_to_measure', 'Never reroll a card to measure it - no respec lever exists and multi-rank cards can return lower. Prefer: character-sheet breakdown tooltips -> gear swaps -> consumables -> buff-state filtering -> two-target comparisons -> bar toggles.', 'Primer', '§5'),
    ('rank_mechanics', 'A card guarantees the MAX RANK of a talent (that\'s the reason to slot one) - X/Y shown is the ROLL result, not spent points, and there is no respec lever. Rolling an upgrade on a held partial-rank card refunds the reroll if it hits; partial-rank talents reportedly have a higher chance of rolling their own upgrade. A 1/1 single-rank card is a cheaper acquisition than chasing a 5-rank card to max.', 'Primer', '§2'),
    ('method_check_icd_before_dilution', 'Before assuming a per-hit proc is diluted by faster/smaller attacks, check whether it has a stated ICD. No-ICD per-hit procs (Fel Infused Weapon, v6) scale UP with attack frequency - the opposite of the usual averaging intuition.', 'Primer', '§5'),
    ('class_tag_proof_case_2', 'Molten Earth is triggered by Lava Lash (Shaman) but its own tooltip confirms "uses Fire Nova modifiers" - a DIFFERENT modifier bucket. Elemental Fusion and Lava Flows buff Lava Lash directly but do NOT buff Molten Earth, despite the trigger relationship. A recommendation assuming otherwise was made and retracted same-session. Corollary: never assume a spawned/triggered secondary effect inherits its trigger\'s modifier bucket by proximity - check its own "uses X modifiers" line independently. Second proof case for the class-tag rule alongside Lightbound Cleave/Cleave.', 'Primer', '§4 (v7)'),
    ('hybrid_ap_sp_not_strike_exclusive', 'AP+SP dual scaling is not exclusive to the named hybrid -strike schools (Holystrike/Firestrike/etc). Molten Earth (pure Fire, 60+(SP+AP)*0.12/tick) and Cataclysmic Sundering (pure Fire ground patch) both mix AP+SP coefficients without being -strike schools. Do not use "-strike naming" as a proxy for "has dual AP+SP scaling" - check raw tooltip coefficients directly every time.', 'Primer', '§1 (v7)'),
    ('weapon_imbue_exclusivity', 'Weapon-imbue-type ability cards (Windfury Weapon, Flametongue Weapon, Fel Infused Weapon, Rockbiter Weapon, Frostbrand Weapon) share a weapon-enchant slot - only one active at a time. This is a mechanical slot conflict, separate from the talent all-damage% exclusivity bucket, and is NOT stated in any single tooltip - ask "is this an imbue?" before recommending one alongside another.', 'Primer', '§2 (v7)'),
    ('method_prefer_named_effect_talents', 'When hunting multipliers for a specific effect (e.g. Shadowflame damage), prefer talents that name the effect verbatim in their tooltip (Shadow and Flame, Bane both list "Shadowflame" explicitly) over talents matched by generic school wording (Emberstorm: "Fire and Shadow spells", does not name Shadowflame - a prediction under the hybrid double-dip rule, not a confirmed hit). Named lists are ground truth; generic wording needs a proc-test.', 'Primer', '§5 (v7)'),
    ('method_rank_id_decoding', 'When decoding a live in-game spell ID export (WeakAura, inspect addon) against the catalog, an unresolved ID is very likely a different rank of a known card, not missing content. Multi-rank talents appear to get a distinct spellID per rank in-game while the catalog stores one canonical ID per card. Check +/-1-3 of the unresolved ID for a known card name before concluding absence. Resolved 5/5 unmatched IDs this way in one live cross-check (Flurry, Vengeance, Fanaticism, Spellblade, Mental Quickness), each landing exactly on a card already known to be held at partial rank.', 'Primer', '§5 (v8)'),
    ('paladin_v6_loadout_confirmed', 'Live inspect/WeakAura export (55 spell IDs) cross-referenced against catalog for Paladin build, 2026-08-02. 22 of 25 v5 board talents confirmed unchanged. Shadow Strikes, Enhanced Weapon Mastery, and Seals of the Pure confirmed rerolled away since v5, replaced by Accuracy, Glyph of Seal of Command (deliberate temporary mana fix pending Spellblade 3/3), and Glyph of Blood Strike (unevaluated filler). Lunar Guidance independently confirmed slotted, matching the v5 hypothesis for the residual Duality SP gap. Berserker Stance, Ghost Wolf, Frostfall confirmed present but player-rated as low-priority leftovers, not core rotation.', 'Handoff', '§7/§12 (v6)'),
    ('goak_avenging_wrath_retraction', 'RETRACTED (v7): "Avenging Wrath / Guardian of Ancient Kings are substitutes, take the first" was wrong. They are independent cooldowns on separate systems - Guardian of Ancient Kings resets/discounts Hammer of the Righteous, Divine Storm, and Holy Shock cooldowns plus a Holy damage buff; Avenging Wrath is a flat all-damage/healing cooldown on its own timer. Both tooltips carry a "does not stack with other similar effects" clause, but that governs multiple instances of the SAME buff type, not necessarily exclusivity between these two specifically - and even under a worst-case mutual-exclusivity reading, sequential use on two separate cooldowns still nets more total burst-window uptime than picking only one. Both moved to the Paladin handoff chase list.', 'Handoff', '§8/§12 (v7)'),
    ('cross_character_ewm_observation', 'Cross-character observation (not a measurement, treat as evidence): Enhanced Weapon Mastery confirmed live (undisputed) on another player\'s comparable Paladin/Hammerdin spec, since his board carries none of the all-damage% exclusivity bucket\'s other members (no Answered Prayers, Unending Fury, Blessed Weapons, Blood Gorged, Improved Blood Presence). Same card is dead on our own build (bucket-blocked by Answered Prayers). Illustrates that a card\'s dead/alive status depends on full board composition, not the card in isolation.', 'Handoff', '§12 (v7)'),
    ('divine_storm_execution_sentence_sighting', 'Cross-character observation (not a measurement): another player\'s comparable Paladin/Hammerdin spec runs both Divine Storm and Execution Sentence live - both are on our own ability chase list (§8). Evidence they are obtainable and playable; not a substitute for our own parse data once acquired.', 'Handoff', '§8 (v7)'),
]

cur.executemany('INSERT INTO confirmed_facts (topic, fact, source_doc, source_section) VALUES (?,?,?,?)',
                 [(t, f, d, s) for (t, f, d, s) in FACTS])

conn.commit()
cur.execute('SELECT COUNT(*) FROM spells WHERE class_origin IS NOT NULL')
print('spells with confirmed class_origin:', cur.fetchone()[0])
cur.execute('SELECT COUNT(*) FROM confirmed_facts')
print('confirmed_facts rows:', cur.fetchone()[0])
conn.close()
