#!/usr/bin/env python3
"""
pet_families.py -- what the log corpus can and cannot say about pets.

STATUS: FINDING 2026-08-08. Written and run once, against the corpus below.
Not maintained; re-run it rather than citing its prose.

    corpus   data/derived/builds.db, mtime 2026-08-08, PRAGMA user_version = 1
    scope    1,212 pet-owning characters / 23,237 pet_ability_damage rows
             251 characters with BOTH a snapshot and pet damage
    command  py tools/analysis/pet_families.py

-------------------------------------------------------------------------------
WHY THIS EXISTS

Asked: "which pet should a Beast Mastery build go tame?" The corpus has pet
DAMAGE but no pet IDENTITY -- no family column, and a pet's display name is
player-chosen. This script tests how far ability-fingerprinting gets you, and
reports the answer honestly when it does not get far.

-------------------------------------------------------------------------------
WHAT IT MEASURED (all figures generated by this script on the corpus above)

1. THE TABLE IS DAMAGE-ONLY. 0 of 23,237 rows carry zero damage. Every
   non-damaging pet ability is invisible BY CONSTRUCTION. For those,
   "absent" means "unmeasurable", never "unused". This is the single most
   important caveat in this file.

2. EXOTIC GATING IS CONFIRMED FOR EXACTLY ONE ABILITY.
       ability                owners w/ snapshot   of which Beast Mastery
       Monstrous Bite                  4                   4      <- gated
       Acid Spit                       7                   0
       Corrosive Acid Breath           8                   0
       Stomp                           8                   0
   So Monstrous Bite (Devilsaur) is a usable exotic fingerprint. The stock
   3.3.5 names are NOT -- Acid Spit / Corrosive Acid Breath / Stomp appear on
   characters who cannot tame exotics.

3. EVERY OTHER 3.3.5 EXOTIC SIGNATURE IS ABSENT: Lava Breath, Ancient
   Hysteria, Froststorm Breath, Venom Web Spray, Qiraji Fortitude, Spirit
   Strike, Spirit Mend -- 0 rows each. Froststorm Breath and Lava Breath DO
   deal damage in stock 3.3.5, so their absence is real evidence of non-use.
   The rest are non-damaging and fall under caveat 1.

4. THE PET TALENT TREES DO NOT APPEAR TO EXIST ON ASCENSION. 17 pet-tree
   signature talents (Spiked Collar, Wild Hunt, Culling the Herd, Feeding
   Frenzy, Shark Attack, Roar of Recovery, Boar's Speed, Great Stamina,
   Natural Armor, Bloodthirsty, Owl's Focus, Cornered, Grace of the Mantis,
   Silverback, Heart of the Phoenix, Lick Your Wounds, Carrion Feeder):
   0 hits across 251 snapshots x 55 cards, and 0 in the 3,061-row card
   catalog. "Cunning" does not exist at all.
   *** TRAP: the cards NAMED "Ferocity" and "Tenacity" are NOT pet specs. ***
   Ferocity is the feral druid talent (Swipe/Claw/Rake/Mangle energy cost);
   Tenacity is "+2% armor from items". Do not read them as pet trees.
   The Beast Mastery card instead grants "+6 Pet Skill Points" -- a system
   with no WotLK equivalent. Caveat 1 applies: pet-tree passives emit no
   damage events, so the CARD absence is the load-bearing evidence, not the
   log absence. Confirm in-game before treating this as settled.

5. FAMILY IS NOT THE LEVER; THE CARD PACKAGE IS. Normalised on Bite damage
   per hit (a basic attack every beast has, owners with >=100 hits), the
   corpus splits into two clusters ~20x apart, and the split tracks build:
       Billyeye   5,138/hit  NO exotic     <- best in corpus
       Deleted    3,432/hit  Devilsaur
       Thajoint   2,459/hit  Devilsaur
       Feathersax 2,201/hit  NO exotic
       Onur       2,179/hit  Devilsaur
       Kenjin     1,964/hit  Devilsaur
       -- gap --
       Abefroman    462/hit  (14 more, 203 -> 78)
   Exotic and non-exotic interleave inside the beast cluster. Monstrous Bite
   itself is 0.07% (Onur) to 7.9% (Deleted) of its owner's pet damage.

-------------------------------------------------------------------------------
KNOWN LIMITS -- read before quoting any number this prints

  * Pet damage tracks the OWNER's gear and scaling far more than the pet's
    family. NOTHING here normalises for that. Section 6's per-hit view is the
    least-bad control available and it is still not a control.
  * n is tiny. 9 Beast Mastery holders in the whole corpus (8 of them with
    any pet damage at all). Section 5 is anecdote, not a ranking.
  * Section 7's top-12 is dominated by Demonology/Wild-Imp builds, not
    hunter-pet builds -- Firebolt (Wild Imp) is the corpus's #1 pet spell at
    163,965,527. Read its counts as "what the biggest pet-damage builds run",
    NOT as a Beast Mastery package. Beast Mastery is 3/12 there for exactly
    that reason.
  * Owners whose pet never used a signature ability are invisible to
    sections 4-6.
  * Signature names are stock 3.3.5 unless marked GATED below. Verify against
    db.ascension.gg before trusting any unverified row.

Read-only. Never writes. Usage:
    py tools/analysis/pet_families.py [path/to/builds.db]
"""

import os
import re
import sqlite3
import statistics
import sys
from collections import defaultdict

# --------------------------------------------------------------------------
# Fingerprints, tagged by how much this corpus actually supports them.
#
#   GATED       measured: every snapshot-having owner also holds Beast Mastery
#   UNGATED     measured: owners exist who do NOT hold Beast Mastery, so this
#               is not an exotic marker on Ascension whatever it means on 3.3.5
#   UNVERIFIED  stock 3.3.5 name, zero or too few observations to judge
#
# Names sharing a string with a non-pet ability are deliberately EXCLUDED --
# 'Rake'/'Prowl' (druid), 'Ravage', 'Snatch', 'Sting' produced pure noise on
# the first pass (33 bogus "Cat" owners at ~2.5k median pet damage).
# --------------------------------------------------------------------------
SIGNATURES = {
    "Devilsaur":    (["monstrous bite"], "GATED"),
    "Worm?":        (["acid spit", "corrosive acid breath"], "UNGATED"),
    "Unknown/Stomp": (["stomp"], "UNGATED"),
    "Core Hound":   (["lava breath", "ancient hysteria"], "UNVERIFIED"),
    "Chimaera":     (["froststorm breath"], "UNVERIFIED"),
    "Silithid":     (["venom web spray", "qiraji fortitude"], "UNVERIFIED"),
    "Spirit Beast": (["spirit strike", "spirit mend"], "UNVERIFIED"),
    "Wolf":         (["furious howl"], "UNVERIFIED"),
    "Wind Serpent": (["lightning breath"], "UNVERIFIED"),
    "Dragonhawk":   (["fire breath"], "UNVERIFIED"),
    "Bat":          (["sonic blast"], "UNVERIFIED"),
    "Sporebat":     (["spore cloud"], "UNVERIFIED"),
    "Nether Ray":   (["nether shock"], "UNVERIFIED"),
}

# The cards that actually predicted pet damage in this corpus. Not a family
# question -- see docstring finding 5.
PET_PACKAGE = [
    "Beast Mastery", "Frenzy Shot", "Kindred Spirits", "Unleashed Fury",
    "Demonic Tactics", "Animal Handler", "Barbed Shot", "Focused Fire",
    "Go for the Throat", "Cobra Strikes", "Bestial Wrath", "The Beast Within",
    "Stampede", "Fetch Me Their Bones!", "Kill Command", "Pack Tactics",
]

# Cards that LOOK like pet specs and are not. Printed as a warning so the next
# reader does not repeat the mistake.
FALSE_FRIENDS = {
    "Ferocity": "feral druid talent (Swipe/Claw/Rake/Mangle energy cost)",
    "Tenacity": "+2% armor from items; a tanking card",
    "Primal Tenacity": "Cat Form fear/stun mitigation",
}

CANDIDATE_PATHS = [
    "data/derived/builds.db",
    "data/builds.db",
    "builds.db",
]


def hr(t):
    print("\n" + "=" * 74 + f"\n{t}\n" + "=" * 74)


def locate_db(argv):
    if len(argv) > 1:
        if not os.path.exists(argv[1]):
            sys.exit(f"REFUSE: no file at {argv[1]}")
        return argv[1]
    for p in CANDIDATE_PATHS:
        if os.path.exists(p):
            return p
    for root, _d, files in os.walk("."):
        if "builds.db" in files:
            return os.path.join(root, "builds.db")
    sys.exit("REFUSE: could not find builds.db. Pass the path explicitly.")


def table_exists(cur, name):
    cur.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (name,))
    return cur.fetchone() is not None


def cols(cur, t):
    cur.execute(f"PRAGMA table_info({t})")
    return [r[1] for r in cur.fetchall()]


def pick(names, *pats):
    for p in pats:
        for c in names:
            if re.search(p, c, re.I):
                return c
    return None


def median(xs):
    xs = [x for x in xs if x is not None]
    return statistics.median(xs) if xs else None


def main():
    db = locate_db(sys.argv)
    print(f"builds.db : {os.path.abspath(db)}")
    con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    cur = con.cursor()

    # ---------------------------------------------------------------- 1
    hr("1. CORPUS SANITY")
    cur.execute("PRAGMA user_version")
    uv = cur.fetchone()[0]
    print(f"PRAGMA user_version = {uv}  (E15 fix landed in 3i; expect >= 1)")

    legacy = False
    if table_exists(cur, "ability_performance") and "is_pet" in cols(cur, "ability_performance"):
        cur.execute("SELECT COUNT(*) FROM ability_performance WHERE is_pet=1")
        n = cur.fetchone()[0]
        print(f"ability_performance rows with is_pet=1 : {n}")
        if n:
            legacy = True
            print("\n  *** PRE-3i DATABASE -- E15 double-count is live. ***")
            print("  Owner DPS is inflated and compute_damage_share / demand_list")
            print("  double-count. Rebuild before trusting anything below:")
            print("      py ingest/logs_gg/build_builds_db.py\n")

    if not table_exists(cur, "pet_ability_damage"):
        print("\npet_ability_damage ABSENT -- pre-3i corpus or pet ingest never ran.")
        print("Rebuild, then re-run. Stopping.")
        return

    pad = cols(cur, "pet_ability_damage")
    name_col = pick(pad, r"^spell_name$", r"name")
    dmg_col = pick(pad, r"^damage_total$", r"^total_damage$", r"^damage$", r"damage")
    char_col = pick(pad, r"^character_id$", r"character", r"owner")
    hits_col = pick(pad, r"^hits$")
    if not (name_col and dmg_col and char_col):
        print(f"REFUSE: schema changed. name={name_col!r} dmg={dmg_col!r} owner={char_col!r}")
        print(f"        columns present: {pad}")
        return
    print(f"schema  : name={name_col} damage={dmg_col} owner={char_col} hits={hits_col}")

    cur.execute("SELECT COUNT(*) FROM pet_ability_damage")
    n_rows = cur.fetchone()[0]
    cur.execute(f"SELECT COUNT(DISTINCT {char_col}) FROM pet_ability_damage")
    n_owners = cur.fetchone()[0]
    print(f"rows    : {n_rows:,}   distinct pet-owning characters: {n_owners:,}")
    if not n_rows:
        print("EMPTY. Nothing to infer. Stopping.")
        return

    # ---------------------------------------------------------------- 2
    hr("2. BLIND SPOT CHECK -- is this table damage-only?")
    cur.execute(f"SELECT COUNT(*) FROM pet_ability_damage WHERE {dmg_col} IS NULL OR {dmg_col}=0")
    zero = cur.fetchone()[0]
    print(f"rows with zero/NULL damage: {zero} of {n_rows:,}")
    if zero == 0:
        print("\n  DAMAGE-ONLY CONFIRMED. Every non-damaging pet ability is invisible")
        print("  by construction -- Furious Howl, Ancient Hysteria, Roar of Courage,")
        print("  Venom Web Spray, and every pet-tree passive.")
        print("  For those, ABSENT means UNMEASURABLE, not unused.")

    # ---------------------------------------------------------------- 3
    hr("3. PET SPELLS BY DAMAGE (top 25)")
    cur.execute(f"""SELECT {name_col}, COUNT(DISTINCT {char_col}), SUM({dmg_col})
                    FROM pet_ability_damage GROUP BY {name_col}
                    ORDER BY 3 DESC LIMIT 25""")
    print(f"  {'spell':<36}{'owners':>8}{'damage':>16}")
    print("  " + "-" * 60)
    for s, o, d in cur.fetchall():
        print(f"  {str(s)[:35]:<36}{o:>8}{int(d or 0):>16,}")

    # ---------------------------------------------------------------- 4
    has_cards = table_exists(cur, "snapshot_cards") and table_exists(cur, "character_snapshots")
    hr("4. SIGNATURE ABILITIES, AND WHETHER THEY ARE EXOTIC-GATED")
    if not has_cards:
        print("  snapshot_cards/character_snapshots absent -- gating cannot be tested.")
    print(f"  {'family':<16}{'tag':<12}{'owners':>8}{'w/snap':>8}{'w/BeastMastery':>16}")
    print("  " + "-" * 60)
    owner_families = defaultdict(set)
    for fam, (sigs, tag) in SIGNATURES.items():
        ids = set()
        for sig in sigs:
            cur.execute(f"SELECT DISTINCT {char_col} FROM pet_ability_damage "
                        f"WHERE LOWER({name_col}) LIKE ?", (f"%{sig}%",))
            ids |= {r[0] for r in cur.fetchall()}
        snap = bm = 0
        for cid in ids:
            owner_families[cid].add(fam)
            if has_cards:
                cur.execute("SELECT 1 FROM character_snapshots WHERE character_id=? LIMIT 1", (cid,))
                if cur.fetchone():
                    snap += 1
                    cur.execute("""SELECT 1 FROM snapshot_cards sc
                                   JOIN character_snapshots cs USING(snapshot_id)
                                   WHERE cs.character_id=? AND sc.name='Beast Mastery' LIMIT 1""", (cid,))
                    if cur.fetchone():
                        bm += 1
        verdict = f"{bm}/{snap}" + (" GATED" if snap and bm == snap else "")
        print(f"  {fam:<16}{tag:<12}{len(ids):>8}{snap:>8}{verdict:>16}")
    print("\n  A family is only a usable exotic marker when w/BeastMastery == w/snap")
    print("  AND w/snap is non-trivial. Anything else is a stock-3.3.5 guess.")

    # ---------------------------------------------------------------- 5
    if has_cards:
        hr("5. BEAST MASTERY HOLDERS -- the only measured exotic cohort")
        cur.execute("""SELECT ch.character_id, ch.name FROM characters ch
                       JOIN character_snapshots cs USING(character_id)
                       JOIN snapshot_cards sc USING(snapshot_id)
                       WHERE sc.name='Beast Mastery' GROUP BY ch.character_id""")
        holders = cur.fetchall()
        print(f"  {len(holders)} in corpus"
              f"{'  -- n too small to rank; treat as anecdote' if len(holders) < 20 else ''}")
        print(f"\n  {'name':<15}{'pet dmg':>14}{'pet/owner':>11}{'avgDPS':>9}{'n>=60s':>8}")
        print("  " + "-" * 57)
        rows = []
        for cid, nm in holders:
            cur.execute(f"SELECT COALESCE(SUM({dmg_col}),0) FROM pet_ability_damage WHERE {char_col}=?", (cid,))
            pd_ = cur.fetchone()[0]
            cur.execute("SELECT COALESCE(SUM(total_damage),0) FROM encounter_performance WHERE character_id=?", (cid,))
            od = cur.fetchone()[0]
            cur.execute("""SELECT AVG(ep.dps), COUNT(*) FROM encounter_performance ep
                           JOIN encounters e USING(encounter_id)
                           WHERE ep.character_id=? AND e.is_trash=0 AND e.duration_seconds>=60""", (cid,))
            avg, n60 = cur.fetchone()
            rows.append((nm, pd_, (pd_ / od * 100 if od else None), avg or 0, n60 or 0))
        for nm, pd_, sh, avg, n60 in sorted(rows, key=lambda r: -r[1]):
            print(f"  {str(nm)[:14]:<15}{int(pd_):>14,}{(f'{sh:.0f}%' if sh else 'n/a'):>11}{avg:>9.0f}{n60:>8}")

        cur.execute("""SELECT ep.dps FROM encounter_performance ep JOIN encounters e USING(encounter_id)
                       WHERE e.is_trash=0 AND e.duration_seconds>=60 AND ep.dps>100 ORDER BY ep.dps""")
        allv = [r[0] for r in cur.fetchall()]
        if allv:
            pcts = " · ".join(f"p{int(q*100)} {allv[int(q*len(allv))]:,.0f}" for q in (0.5, 0.75, 0.9, 0.95))
            print(f"\n  corpus reference, boss fights >=60s (n={len(allv):,}): {pcts}")

        hr("5b. FALSE FRIENDS -- cards that look like pet specs and are not")
        for nm, why in FALSE_FRIENDS.items():
            cur.execute("SELECT COUNT(DISTINCT snapshot_id) FROM snapshot_cards WHERE name=?", (nm,))
            print(f"  {nm:<18} in {cur.fetchone()[0]:>4} snapshots -- {why}")

    # ---------------------------------------------------------------- 6
    hr("6. NORMALISED: 'Bite' damage per hit, exotic vs not")
    if not hits_col:
        print("  no hits column -- cannot normalise. Skipping.")
    else:
        cur.execute(f"""SELECT p.{char_col}, ch.name,
                               SUM(p.{dmg_col})*1.0/NULLIF(SUM(p.{hits_col}),0), SUM(p.{hits_col})
                        FROM pet_ability_damage p LEFT JOIN characters ch USING(character_id)
                        WHERE p.{name_col}='Bite' GROUP BY p.{char_col}
                        HAVING SUM(p.{hits_col})>=100""")
        out = []
        for cid, nm, ph, h in cur.fetchall():
            cur.execute(f"SELECT 1 FROM pet_ability_damage WHERE {char_col}=? "
                        f"AND LOWER({name_col}) LIKE '%monstrous bite%'", (cid,))
            out.append((nm, ph, h, bool(cur.fetchone())))
        out.sort(key=lambda x: -(x[1] or 0))
        print(f"  {'name':<16}{'Bite/hit':>10}{'hits':>8}{'exotic':>10}")
        print("  " + "-" * 44)
        for nm, ph, h, e in out[:20]:
            print(f"  {str(nm)[:15]:<16}{ph:>10.0f}{int(h):>8}{'DEVILSAUR' if e else '-':>10}")
        exo = [x[1] for x in out if x[3]]
        non = [x[1] for x in out if not x[3]]
        if exo and non:
            print(f"\n  Devilsaur  n={len(exo):<3} median {median(exo):,.0f}/hit")
            print(f"  other      n={len(non):<3} median {median(non):,.0f}/hit")
            print("\n  DO NOT read that ratio as an exotic advantage. The 'other' group is")
            print("  mostly incidental pets with no pet cards. Inside the top cluster,")
            print("  exotic and non-exotic interleave -- see docstring finding 5.")

    # ---------------------------------------------------------------- 7
    if has_cards:
        hr("7. THE CARD PACKAGE -- what actually predicted pet damage")
        cur.execute(f"""SELECT ch.character_id, ch.name, SUM(p.{dmg_col})
                        FROM pet_ability_damage p JOIN characters ch USING(character_id)
                        WHERE EXISTS(SELECT 1 FROM character_snapshots cs
                                     WHERE cs.character_id=ch.character_id)
                        GROUP BY ch.character_id ORDER BY 3 DESC LIMIT 12""")
        top = cur.fetchall()
        print(f"  presence among the top {len(top)} pet-damage builds that have a snapshot:")
        for card in PET_PACKAGE:
            k = 0
            for cid, _n, _d in top:
                cur.execute("""SELECT 1 FROM snapshot_cards sc JOIN character_snapshots cs
                               USING(snapshot_id) WHERE cs.character_id=? AND sc.name=? LIMIT 1""",
                            (cid, card))
                k += bool(cur.fetchone())
            bar = "#" * k
            print(f"    {k:>2}/{len(top)}  {card:<24}{bar}")

    hr("CAVEATS -- see the module docstring for the full list")
    print("  * Pet damage tracks OWNER gear far more than pet family. Not controlled.")
    print("  * Non-damaging pet abilities are invisible (section 2).")
    print("  * Unverified signatures are stock 3.3.5 guesses; check db.ascension.gg.")
    print("  * Owners whose pet never used a signature are absent from 4-6.")
    if legacy:
        print("  * AND THIS DB IS PRE-3i -- every figure above is double-counted.")
    con.close()


if __name__ == "__main__":
    main()
